/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type IncentiveKeyStruct = {
  rewardToken: AddressLike;
  bonusRewardToken: AddressLike;
  pool: AddressLike;
  nonce: BigNumberish;
};

export type IncentiveKeyStructOutput = [
  rewardToken: string,
  bonusRewardToken: string,
  pool: string,
  nonce: bigint
] & {
  rewardToken: string;
  bonusRewardToken: string;
  pool: string;
  nonce: bigint;
};

export declare namespace IAlgebraEternalFarming {
  export type IncentiveParamsStruct = {
    reward: BigNumberish;
    bonusReward: BigNumberish;
    rewardRate: BigNumberish;
    bonusRewardRate: BigNumberish;
    minimalPositionWidth: BigNumberish;
  };

  export type IncentiveParamsStructOutput = [
    reward: bigint,
    bonusReward: bigint,
    rewardRate: bigint,
    bonusRewardRate: bigint,
    minimalPositionWidth: bigint
  ] & {
    reward: bigint;
    bonusReward: bigint;
    rewardRate: bigint;
    bonusRewardRate: bigint;
    minimalPositionWidth: bigint;
  };
}

export interface AlgebraEternalFarmingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FARMINGS_ADMINISTRATOR_ROLE"
      | "INCENTIVE_MAKER_ROLE"
      | "addRewards"
      | "claimReward"
      | "claimRewardFrom"
      | "collectRewards"
      | "createEternalFarming"
      | "deactivateIncentive"
      | "decreaseRewardsAmount"
      | "enterFarming"
      | "exitFarming"
      | "farmingCenter"
      | "farms"
      | "getRewardInfo"
      | "incentiveKeys"
      | "incentives"
      | "isEmergencyWithdrawActivated"
      | "isIncentiveDeactivated"
      | "nonfungiblePositionManager"
      | "numOfIncentives"
      | "rewards"
      | "setEmergencyWithdrawStatus"
      | "setFarmingCenterAddress"
      | "setRates"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EmergencyWithdraw"
      | "EternalFarmingCreated"
      | "FarmEnded"
      | "FarmEntered"
      | "FarmingCenter"
      | "IncentiveDeactivated"
      | "RewardAmountsDecreased"
      | "RewardClaimed"
      | "RewardsAdded"
      | "RewardsCollected"
      | "RewardsRatesChanged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "FARMINGS_ADMINISTRATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INCENTIVE_MAKER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addRewards",
    values: [IncentiveKeyStruct, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimReward",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRewardFrom",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collectRewards",
    values: [IncentiveKeyStruct, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createEternalFarming",
    values: [
      IncentiveKeyStruct,
      IAlgebraEternalFarming.IncentiveParamsStruct,
      AddressLike,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateIncentive",
    values: [IncentiveKeyStruct, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "decreaseRewardsAmount",
    values: [IncentiveKeyStruct, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "enterFarming",
    values: [IncentiveKeyStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "exitFarming",
    values: [IncentiveKeyStruct, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "farmingCenter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "farms",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRewardInfo",
    values: [IncentiveKeyStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "incentiveKeys",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "incentives",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isEmergencyWithdrawActivated",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isIncentiveDeactivated",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nonfungiblePositionManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "numOfIncentives",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewards",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setEmergencyWithdrawStatus",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setFarmingCenterAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRates",
    values: [IncentiveKeyStruct, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "FARMINGS_ADMINISTRATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INCENTIVE_MAKER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addRewards", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRewardFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEternalFarming",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateIncentive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decreaseRewardsAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enterFarming",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "exitFarming",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "farmingCenter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "farms", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRewardInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "incentiveKeys",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "incentives", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isEmergencyWithdrawActivated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isIncentiveDeactivated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nonfungiblePositionManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numOfIncentives",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rewards", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setEmergencyWithdrawStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFarmingCenterAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRates", data: BytesLike): Result;
}

export namespace EmergencyWithdrawEvent {
  export type InputTuple = [newStatus: boolean];
  export type OutputTuple = [newStatus: boolean];
  export interface OutputObject {
    newStatus: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EternalFarmingCreatedEvent {
  export type InputTuple = [
    rewardToken: AddressLike,
    bonusRewardToken: AddressLike,
    pool: AddressLike,
    virtualPool: AddressLike,
    nonce: BigNumberish,
    reward: BigNumberish,
    bonusReward: BigNumberish,
    minimalAllowedPositionWidth: BigNumberish
  ];
  export type OutputTuple = [
    rewardToken: string,
    bonusRewardToken: string,
    pool: string,
    virtualPool: string,
    nonce: bigint,
    reward: bigint,
    bonusReward: bigint,
    minimalAllowedPositionWidth: bigint
  ];
  export interface OutputObject {
    rewardToken: string;
    bonusRewardToken: string;
    pool: string;
    virtualPool: string;
    nonce: bigint;
    reward: bigint;
    bonusReward: bigint;
    minimalAllowedPositionWidth: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FarmEndedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    incentiveId: BytesLike,
    rewardAddress: AddressLike,
    bonusRewardToken: AddressLike,
    owner: AddressLike,
    reward: BigNumberish,
    bonusReward: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    incentiveId: string,
    rewardAddress: string,
    bonusRewardToken: string,
    owner: string,
    reward: bigint,
    bonusReward: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    incentiveId: string;
    rewardAddress: string;
    bonusRewardToken: string;
    owner: string;
    reward: bigint;
    bonusReward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FarmEnteredEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    incentiveId: BytesLike,
    liquidity: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    incentiveId: string,
    liquidity: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    incentiveId: string;
    liquidity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FarmingCenterEvent {
  export type InputTuple = [farmingCenter: AddressLike];
  export type OutputTuple = [farmingCenter: string];
  export interface OutputObject {
    farmingCenter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IncentiveDeactivatedEvent {
  export type InputTuple = [incentiveId: BytesLike];
  export type OutputTuple = [incentiveId: string];
  export interface OutputObject {
    incentiveId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardAmountsDecreasedEvent {
  export type InputTuple = [
    rewardAmount: BigNumberish,
    bonusRewardAmount: BigNumberish,
    incentiveId: BytesLike
  ];
  export type OutputTuple = [
    rewardAmount: bigint,
    bonusRewardAmount: bigint,
    incentiveId: string
  ];
  export interface OutputObject {
    rewardAmount: bigint;
    bonusRewardAmount: bigint;
    incentiveId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardClaimedEvent {
  export type InputTuple = [
    to: AddressLike,
    reward: BigNumberish,
    rewardAddress: AddressLike,
    owner: AddressLike
  ];
  export type OutputTuple = [
    to: string,
    reward: bigint,
    rewardAddress: string,
    owner: string
  ];
  export interface OutputObject {
    to: string;
    reward: bigint;
    rewardAddress: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsAddedEvent {
  export type InputTuple = [
    rewardAmount: BigNumberish,
    bonusRewardAmount: BigNumberish,
    incentiveId: BytesLike
  ];
  export type OutputTuple = [
    rewardAmount: bigint,
    bonusRewardAmount: bigint,
    incentiveId: string
  ];
  export interface OutputObject {
    rewardAmount: bigint;
    bonusRewardAmount: bigint;
    incentiveId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsCollectedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    incentiveId: BytesLike,
    rewardAmount: BigNumberish,
    bonusRewardAmount: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    incentiveId: string,
    rewardAmount: bigint,
    bonusRewardAmount: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    incentiveId: string;
    rewardAmount: bigint;
    bonusRewardAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsRatesChangedEvent {
  export type InputTuple = [
    rewardRate: BigNumberish,
    bonusRewardRate: BigNumberish,
    incentiveId: BytesLike
  ];
  export type OutputTuple = [
    rewardRate: bigint,
    bonusRewardRate: bigint,
    incentiveId: string
  ];
  export interface OutputObject {
    rewardRate: bigint;
    bonusRewardRate: bigint;
    incentiveId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AlgebraEternalFarming extends BaseContract {
  connect(runner?: ContractRunner | null): AlgebraEternalFarming;
  waitForDeployment(): Promise<this>;

  interface: AlgebraEternalFarmingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FARMINGS_ADMINISTRATOR_ROLE: TypedContractMethod<[], [string], "view">;

  INCENTIVE_MAKER_ROLE: TypedContractMethod<[], [string], "view">;

  addRewards: TypedContractMethod<
    [
      key: IncentiveKeyStruct,
      rewardAmount: BigNumberish,
      bonusRewardAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  claimReward: TypedContractMethod<
    [rewardToken: AddressLike, to: AddressLike, amountRequested: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  claimRewardFrom: TypedContractMethod<
    [
      rewardToken: AddressLike,
      from: AddressLike,
      to: AddressLike,
      amountRequested: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  collectRewards: TypedContractMethod<
    [key: IncentiveKeyStruct, tokenId: BigNumberish, _owner: AddressLike],
    [[bigint, bigint] & { reward: bigint; bonusReward: bigint }],
    "nonpayable"
  >;

  createEternalFarming: TypedContractMethod<
    [
      key: IncentiveKeyStruct,
      params: IAlgebraEternalFarming.IncentiveParamsStruct,
      plugin: AddressLike,
      customPoolDeployer: AddressLike
    ],
    [string],
    "nonpayable"
  >;

  deactivateIncentive: TypedContractMethod<
    [key: IncentiveKeyStruct, customPoolDeployer: AddressLike],
    [void],
    "nonpayable"
  >;

  decreaseRewardsAmount: TypedContractMethod<
    [
      key: IncentiveKeyStruct,
      rewardAmount: BigNumberish,
      bonusRewardAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  enterFarming: TypedContractMethod<
    [key: IncentiveKeyStruct, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  exitFarming: TypedContractMethod<
    [key: IncentiveKeyStruct, tokenId: BigNumberish, _owner: AddressLike],
    [void],
    "nonpayable"
  >;

  farmingCenter: TypedContractMethod<[], [string], "view">;

  farms: TypedContractMethod<
    [tokenId: BigNumberish, incentiveId: BytesLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        liquidity: bigint;
        tickLower: bigint;
        tickUpper: bigint;
        innerRewardGrowth0: bigint;
        innerRewardGrowth1: bigint;
      }
    ],
    "view"
  >;

  getRewardInfo: TypedContractMethod<
    [key: IncentiveKeyStruct, tokenId: BigNumberish],
    [[bigint, bigint] & { reward: bigint; bonusReward: bigint }],
    "view"
  >;

  incentiveKeys: TypedContractMethod<
    [pool: AddressLike],
    [
      [string, string, string, bigint] & {
        rewardToken: string;
        bonusRewardToken: string;
        pool: string;
        nonce: bigint;
      }
    ],
    "view"
  >;

  incentives: TypedContractMethod<
    [incentiveId: BytesLike],
    [
      [bigint, bigint, string, bigint, boolean, string] & {
        totalReward: bigint;
        bonusReward: bigint;
        virtualPoolAddress: string;
        minimalPositionWidth: bigint;
        deactivated: boolean;
        pluginAddress: string;
      }
    ],
    "view"
  >;

  isEmergencyWithdrawActivated: TypedContractMethod<[], [boolean], "view">;

  isIncentiveDeactivated: TypedContractMethod<
    [incentiveId: BytesLike],
    [boolean],
    "view"
  >;

  nonfungiblePositionManager: TypedContractMethod<[], [string], "view">;

  numOfIncentives: TypedContractMethod<[], [bigint], "view">;

  rewards: TypedContractMethod<
    [owner: AddressLike, rewardToken: AddressLike],
    [bigint],
    "view"
  >;

  setEmergencyWithdrawStatus: TypedContractMethod<
    [newStatus: boolean],
    [void],
    "nonpayable"
  >;

  setFarmingCenterAddress: TypedContractMethod<
    [_farmingCenter: AddressLike],
    [void],
    "nonpayable"
  >;

  setRates: TypedContractMethod<
    [
      key: IncentiveKeyStruct,
      rewardRate: BigNumberish,
      bonusRewardRate: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FARMINGS_ADMINISTRATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INCENTIVE_MAKER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addRewards"
  ): TypedContractMethod<
    [
      key: IncentiveKeyStruct,
      rewardAmount: BigNumberish,
      bonusRewardAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimReward"
  ): TypedContractMethod<
    [rewardToken: AddressLike, to: AddressLike, amountRequested: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimRewardFrom"
  ): TypedContractMethod<
    [
      rewardToken: AddressLike,
      from: AddressLike,
      to: AddressLike,
      amountRequested: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "collectRewards"
  ): TypedContractMethod<
    [key: IncentiveKeyStruct, tokenId: BigNumberish, _owner: AddressLike],
    [[bigint, bigint] & { reward: bigint; bonusReward: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createEternalFarming"
  ): TypedContractMethod<
    [
      key: IncentiveKeyStruct,
      params: IAlgebraEternalFarming.IncentiveParamsStruct,
      plugin: AddressLike,
      customPoolDeployer: AddressLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deactivateIncentive"
  ): TypedContractMethod<
    [key: IncentiveKeyStruct, customPoolDeployer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "decreaseRewardsAmount"
  ): TypedContractMethod<
    [
      key: IncentiveKeyStruct,
      rewardAmount: BigNumberish,
      bonusRewardAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "enterFarming"
  ): TypedContractMethod<
    [key: IncentiveKeyStruct, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "exitFarming"
  ): TypedContractMethod<
    [key: IncentiveKeyStruct, tokenId: BigNumberish, _owner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "farmingCenter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "farms"
  ): TypedContractMethod<
    [tokenId: BigNumberish, incentiveId: BytesLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        liquidity: bigint;
        tickLower: bigint;
        tickUpper: bigint;
        innerRewardGrowth0: bigint;
        innerRewardGrowth1: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRewardInfo"
  ): TypedContractMethod<
    [key: IncentiveKeyStruct, tokenId: BigNumberish],
    [[bigint, bigint] & { reward: bigint; bonusReward: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "incentiveKeys"
  ): TypedContractMethod<
    [pool: AddressLike],
    [
      [string, string, string, bigint] & {
        rewardToken: string;
        bonusRewardToken: string;
        pool: string;
        nonce: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "incentives"
  ): TypedContractMethod<
    [incentiveId: BytesLike],
    [
      [bigint, bigint, string, bigint, boolean, string] & {
        totalReward: bigint;
        bonusReward: bigint;
        virtualPoolAddress: string;
        minimalPositionWidth: bigint;
        deactivated: boolean;
        pluginAddress: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isEmergencyWithdrawActivated"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isIncentiveDeactivated"
  ): TypedContractMethod<[incentiveId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "nonfungiblePositionManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "numOfIncentives"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "rewards"
  ): TypedContractMethod<
    [owner: AddressLike, rewardToken: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "setEmergencyWithdrawStatus"
  ): TypedContractMethod<[newStatus: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFarmingCenterAddress"
  ): TypedContractMethod<[_farmingCenter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRates"
  ): TypedContractMethod<
    [
      key: IncentiveKeyStruct,
      rewardRate: BigNumberish,
      bonusRewardRate: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "EmergencyWithdraw"
  ): TypedContractEvent<
    EmergencyWithdrawEvent.InputTuple,
    EmergencyWithdrawEvent.OutputTuple,
    EmergencyWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "EternalFarmingCreated"
  ): TypedContractEvent<
    EternalFarmingCreatedEvent.InputTuple,
    EternalFarmingCreatedEvent.OutputTuple,
    EternalFarmingCreatedEvent.OutputObject
  >;
  getEvent(
    key: "FarmEnded"
  ): TypedContractEvent<
    FarmEndedEvent.InputTuple,
    FarmEndedEvent.OutputTuple,
    FarmEndedEvent.OutputObject
  >;
  getEvent(
    key: "FarmEntered"
  ): TypedContractEvent<
    FarmEnteredEvent.InputTuple,
    FarmEnteredEvent.OutputTuple,
    FarmEnteredEvent.OutputObject
  >;
  getEvent(
    key: "FarmingCenter"
  ): TypedContractEvent<
    FarmingCenterEvent.InputTuple,
    FarmingCenterEvent.OutputTuple,
    FarmingCenterEvent.OutputObject
  >;
  getEvent(
    key: "IncentiveDeactivated"
  ): TypedContractEvent<
    IncentiveDeactivatedEvent.InputTuple,
    IncentiveDeactivatedEvent.OutputTuple,
    IncentiveDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "RewardAmountsDecreased"
  ): TypedContractEvent<
    RewardAmountsDecreasedEvent.InputTuple,
    RewardAmountsDecreasedEvent.OutputTuple,
    RewardAmountsDecreasedEvent.OutputObject
  >;
  getEvent(
    key: "RewardClaimed"
  ): TypedContractEvent<
    RewardClaimedEvent.InputTuple,
    RewardClaimedEvent.OutputTuple,
    RewardClaimedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsAdded"
  ): TypedContractEvent<
    RewardsAddedEvent.InputTuple,
    RewardsAddedEvent.OutputTuple,
    RewardsAddedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsCollected"
  ): TypedContractEvent<
    RewardsCollectedEvent.InputTuple,
    RewardsCollectedEvent.OutputTuple,
    RewardsCollectedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsRatesChanged"
  ): TypedContractEvent<
    RewardsRatesChangedEvent.InputTuple,
    RewardsRatesChangedEvent.OutputTuple,
    RewardsRatesChangedEvent.OutputObject
  >;

  filters: {
    "EmergencyWithdraw(bool)": TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;
    EmergencyWithdraw: TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;

    "EternalFarmingCreated(address,address,address,address,uint256,uint256,uint256,uint24)": TypedContractEvent<
      EternalFarmingCreatedEvent.InputTuple,
      EternalFarmingCreatedEvent.OutputTuple,
      EternalFarmingCreatedEvent.OutputObject
    >;
    EternalFarmingCreated: TypedContractEvent<
      EternalFarmingCreatedEvent.InputTuple,
      EternalFarmingCreatedEvent.OutputTuple,
      EternalFarmingCreatedEvent.OutputObject
    >;

    "FarmEnded(uint256,bytes32,address,address,address,uint256,uint256)": TypedContractEvent<
      FarmEndedEvent.InputTuple,
      FarmEndedEvent.OutputTuple,
      FarmEndedEvent.OutputObject
    >;
    FarmEnded: TypedContractEvent<
      FarmEndedEvent.InputTuple,
      FarmEndedEvent.OutputTuple,
      FarmEndedEvent.OutputObject
    >;

    "FarmEntered(uint256,bytes32,uint128)": TypedContractEvent<
      FarmEnteredEvent.InputTuple,
      FarmEnteredEvent.OutputTuple,
      FarmEnteredEvent.OutputObject
    >;
    FarmEntered: TypedContractEvent<
      FarmEnteredEvent.InputTuple,
      FarmEnteredEvent.OutputTuple,
      FarmEnteredEvent.OutputObject
    >;

    "FarmingCenter(address)": TypedContractEvent<
      FarmingCenterEvent.InputTuple,
      FarmingCenterEvent.OutputTuple,
      FarmingCenterEvent.OutputObject
    >;
    FarmingCenter: TypedContractEvent<
      FarmingCenterEvent.InputTuple,
      FarmingCenterEvent.OutputTuple,
      FarmingCenterEvent.OutputObject
    >;

    "IncentiveDeactivated(bytes32)": TypedContractEvent<
      IncentiveDeactivatedEvent.InputTuple,
      IncentiveDeactivatedEvent.OutputTuple,
      IncentiveDeactivatedEvent.OutputObject
    >;
    IncentiveDeactivated: TypedContractEvent<
      IncentiveDeactivatedEvent.InputTuple,
      IncentiveDeactivatedEvent.OutputTuple,
      IncentiveDeactivatedEvent.OutputObject
    >;

    "RewardAmountsDecreased(uint256,uint256,bytes32)": TypedContractEvent<
      RewardAmountsDecreasedEvent.InputTuple,
      RewardAmountsDecreasedEvent.OutputTuple,
      RewardAmountsDecreasedEvent.OutputObject
    >;
    RewardAmountsDecreased: TypedContractEvent<
      RewardAmountsDecreasedEvent.InputTuple,
      RewardAmountsDecreasedEvent.OutputTuple,
      RewardAmountsDecreasedEvent.OutputObject
    >;

    "RewardClaimed(address,uint256,address,address)": TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;
    RewardClaimed: TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;

    "RewardsAdded(uint256,uint256,bytes32)": TypedContractEvent<
      RewardsAddedEvent.InputTuple,
      RewardsAddedEvent.OutputTuple,
      RewardsAddedEvent.OutputObject
    >;
    RewardsAdded: TypedContractEvent<
      RewardsAddedEvent.InputTuple,
      RewardsAddedEvent.OutputTuple,
      RewardsAddedEvent.OutputObject
    >;

    "RewardsCollected(uint256,bytes32,uint256,uint256)": TypedContractEvent<
      RewardsCollectedEvent.InputTuple,
      RewardsCollectedEvent.OutputTuple,
      RewardsCollectedEvent.OutputObject
    >;
    RewardsCollected: TypedContractEvent<
      RewardsCollectedEvent.InputTuple,
      RewardsCollectedEvent.OutputTuple,
      RewardsCollectedEvent.OutputObject
    >;

    "RewardsRatesChanged(uint128,uint128,bytes32)": TypedContractEvent<
      RewardsRatesChangedEvent.InputTuple,
      RewardsRatesChangedEvent.OutputTuple,
      RewardsRatesChangedEvent.OutputObject
    >;
    RewardsRatesChanged: TypedContractEvent<
      RewardsRatesChangedEvent.InputTuple,
      RewardsRatesChangedEvent.OutputTuple,
      RewardsRatesChangedEvent.OutputObject
    >;
  };
}
