/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AlgebraEternalFarming } from "./AlgebraEternalFarming";
export type { EternalVirtualPool } from "./EternalVirtualPool";
