/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockTimeVirtualPool,
  MockTimeVirtualPoolInterface,
} from "../../../contracts/test/MockTimeVirtualPool";

const _abi = [
  {
    inputs: [
      {
        internalType: "int24",
        name: "nextTick",
        type: "int24",
      },
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    name: "crossTo",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "currentTick",
    outputs: [
      {
        internalType: "int24",
        name: "",
        type: "int24",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "setEarlyReturn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "timestamp",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506101b1806100206000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c8063065e53601461005157806334d335901461007d5780636834937f146100b9578063b80777ea146100f2575b600080fd5b60005461006690640100000000900460020b81565b6040805160029290920b8252519081900360200190f35b6100a56004803603604081101561009357600080fd5b50803560020b9060200135151561011b565b604080519115158252519081900360200190f35b6100f0600080547fffffffffffffffffffffffffffffffffffffffffffffffff00ffffffffffffff16670100000000000000179055565b005b6000546101029063ffffffff1681565b6040805163ffffffff9092168252519081900360200190f35b60008054670100000000000000900460ff161561013a5750600161019e565b50600080547fffffffffffffffffffffffffffffffffffffffffffffffffff000000000000001664010000000062ffffff8516027fffffffffffffffffffffffffffffffffffffffffffffffffffffffff0000000016174263ffffffff1617905560015b9291505056fea164736f6c6343000814000a";

type MockTimeVirtualPoolConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockTimeVirtualPoolConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockTimeVirtualPool__factory extends ContractFactory {
  constructor(...args: MockTimeVirtualPoolConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockTimeVirtualPool & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): MockTimeVirtualPool__factory {
    return super.connect(runner) as MockTimeVirtualPool__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockTimeVirtualPoolInterface {
    return new Interface(_abi) as MockTimeVirtualPoolInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockTimeVirtualPool {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as MockTimeVirtualPool;
  }
}
