/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  TestVirtualPool,
  TestVirtualPoolInterface,
} from "../../../contracts/test/TestVirtualPool";

const _abi = [
  {
    inputs: [
      {
        internalType: "int24",
        name: "",
        type: "int24",
      },
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    name: "crossTo",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506101de806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c806334d3359014610030575b600080fd5b6100586004803603604081101561004657600080fd5b50803560020b9060200135151561006c565b604080519115158252519081900360200190f35b6000805b60648110156101685760003373ffffffffffffffffffffffffffffffffffffffff1663e76c01e46040518163ffffffff1660e01b815260040160c060405180830381865afa1580156100c6573d6000803e3d6000fd5b505050506040513d60c08110156100dc57600080fd5b5060209081015160408051928301905260020b81526000805460018101825590805290517f290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e56390910180547fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff0000001662ffffff909216919091179055508061016081610172565b915050610070565b5060019392505050565b60007fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff82036101ca577f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b506001019056fea164736f6c6343000814000a";

type TestVirtualPoolConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TestVirtualPoolConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TestVirtualPool__factory extends ContractFactory {
  constructor(...args: TestVirtualPoolConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      TestVirtualPool & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): TestVirtualPool__factory {
    return super.connect(runner) as TestVirtualPool__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TestVirtualPoolInterface {
    return new Interface(_abi) as TestVirtualPoolInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TestVirtualPool {
    return new Contract(address, _abi, runner) as unknown as TestVirtualPool;
  }
}
