/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";

export interface IFarmingPluginInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getPool"
      | "incentive"
      | "isIncentiveConnected"
      | "setIncentive"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Incentive"): EventFragment;

  encodeFunctionData(functionFragment: "getPool", values?: undefined): string;
  encodeFunctionData(functionFragment: "incentive", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isIncentiveConnected",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setIncentive",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "getPool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "incentive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isIncentiveConnected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setIncentive",
    data: BytesLike
  ): Result;
}

export namespace IncentiveEvent {
  export type InputTuple = [newIncentive: AddressLike];
  export type OutputTuple = [newIncentive: string];
  export interface OutputObject {
    newIncentive: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IFarmingPlugin extends BaseContract {
  connect(runner?: ContractRunner | null): IFarmingPlugin;
  waitForDeployment(): Promise<this>;

  interface: IFarmingPluginInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getPool: TypedContractMethod<[], [string], "view">;

  incentive: TypedContractMethod<[], [string], "view">;

  isIncentiveConnected: TypedContractMethod<
    [targetIncentive: AddressLike],
    [boolean],
    "view"
  >;

  setIncentive: TypedContractMethod<
    [newIncentive: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getPool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "incentive"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isIncentiveConnected"
  ): TypedContractMethod<[targetIncentive: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "setIncentive"
  ): TypedContractMethod<[newIncentive: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "Incentive"
  ): TypedContractEvent<
    IncentiveEvent.InputTuple,
    IncentiveEvent.OutputTuple,
    IncentiveEvent.OutputObject
  >;

  filters: {
    "Incentive(address)": TypedContractEvent<
      IncentiveEvent.InputTuple,
      IncentiveEvent.OutputTuple,
      IncentiveEvent.OutputObject
    >;
    Incentive: TypedContractEvent<
      IncentiveEvent.InputTuple,
      IncentiveEvent.OutputTuple,
      IncentiveEvent.OutputObject
    >;
  };
}
