/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISecurityPlugin,
  ISecurityPluginInterface,
} from "../../../../contracts/interfaces/plugins/ISecurityPlugin";

const _abi = [
  {
    inputs: [],
    name: "BurnOnly",
    type: "error",
  },
  {
    inputs: [],
    name: "PoolDisabled",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "registry",
        type: "address",
      },
    ],
    name: "SecurityRegistry",
    type: "event",
  },
  {
    inputs: [],
    name: "getSecurityRegistry",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "registry",
        type: "address",
      },
    ],
    name: "setSecurityRegistry",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISecurityPlugin__factory {
  static readonly abi = _abi;
  static createInterface(): ISecurityPluginInterface {
    return new Interface(_abi) as ISecurityPluginInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISecurityPlugin {
    return new Contract(address, _abi, runner) as unknown as ISecurityPlugin;
  }
}
