/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface SecurityRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "GUARD"
      | "algebraFactory"
      | "getPoolStatus"
      | "globalStatus"
      | "isPoolStatusOverrided"
      | "poolStatus"
      | "setGlobalStatus"
      | "setPoolsStatus"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "GlobalStatus" | "PoolStatus"
  ): EventFragment;

  encodeFunctionData(functionFragment: "GUARD", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "algebraFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolStatus",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "globalStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isPoolStatusOverrided",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "poolStatus",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setGlobalStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPoolsStatus",
    values: [AddressLike[], BigNumberish[]]
  ): string;

  decodeFunctionResult(functionFragment: "GUARD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "algebraFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPoolStatusOverrided",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "poolStatus", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setGlobalStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPoolsStatus",
    data: BytesLike
  ): Result;
}

export namespace GlobalStatusEvent {
  export type InputTuple = [status: BigNumberish];
  export type OutputTuple = [status: bigint];
  export interface OutputObject {
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolStatusEvent {
  export type InputTuple = [pool: AddressLike, status: BigNumberish];
  export type OutputTuple = [pool: string, status: bigint];
  export interface OutputObject {
    pool: string;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SecurityRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): SecurityRegistry;
  waitForDeployment(): Promise<this>;

  interface: SecurityRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  GUARD: TypedContractMethod<[], [string], "view">;

  algebraFactory: TypedContractMethod<[], [string], "view">;

  getPoolStatus: TypedContractMethod<[pool: AddressLike], [bigint], "view">;

  globalStatus: TypedContractMethod<[], [bigint], "view">;

  isPoolStatusOverrided: TypedContractMethod<[], [boolean], "view">;

  poolStatus: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  setGlobalStatus: TypedContractMethod<
    [newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPoolsStatus: TypedContractMethod<
    [pools: AddressLike[], newStatuses: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "GUARD"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "algebraFactory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPoolStatus"
  ): TypedContractMethod<[pool: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "globalStatus"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isPoolStatusOverrided"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "poolStatus"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setGlobalStatus"
  ): TypedContractMethod<[newStatus: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPoolsStatus"
  ): TypedContractMethod<
    [pools: AddressLike[], newStatuses: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "GlobalStatus"
  ): TypedContractEvent<
    GlobalStatusEvent.InputTuple,
    GlobalStatusEvent.OutputTuple,
    GlobalStatusEvent.OutputObject
  >;
  getEvent(
    key: "PoolStatus"
  ): TypedContractEvent<
    PoolStatusEvent.InputTuple,
    PoolStatusEvent.OutputTuple,
    PoolStatusEvent.OutputObject
  >;

  filters: {
    "GlobalStatus(uint8)": TypedContractEvent<
      GlobalStatusEvent.InputTuple,
      GlobalStatusEvent.OutputTuple,
      GlobalStatusEvent.OutputObject
    >;
    GlobalStatus: TypedContractEvent<
      GlobalStatusEvent.InputTuple,
      GlobalStatusEvent.OutputTuple,
      GlobalStatusEvent.OutputObject
    >;

    "PoolStatus(address,uint8)": TypedContractEvent<
      PoolStatusEvent.InputTuple,
      PoolStatusEvent.OutputTuple,
      PoolStatusEvent.OutputObject
    >;
    PoolStatus: TypedContractEvent<
      PoolStatusEvent.InputTuple,
      PoolStatusEvent.OutputTuple,
      PoolStatusEvent.OutputObject
    >;
  };
}
