/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPositionFollower,
  IPositionFollowerInterface,
} from "../../../../../@cryptoalgebra/integral-periphery/contracts/interfaces/IPositionFollower";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "int256",
        name: "liquidityDelta",
        type: "int256",
      },
    ],
    name: "applyLiquidityDelta",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPositionFollower__factory {
  static readonly abi = _abi;
  static createInterface(): IPositionFollowerInterface {
    return new Interface(_abi) as IPositionFollowerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPositionFollower {
    return new Contract(address, _abi, runner) as unknown as IPositionFollower;
  }
}
