/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IReflexRouter,
  IReflexRouterInterface,
} from "../../../../../contracts/interfaces/plugins/reflex-mev/IReflexRouter";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "triggerPoolId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint112",
        name: "swapAmountIn",
        type: "uint112",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "token0In",
        type: "bool",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "quoteProfit",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "profit",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "profitToken",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "recipient",
        type: "address",
      },
    ],
    name: "BackrunExecuted",
    type: "event",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "target",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "value",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "callData",
            type: "bytes",
          },
        ],
        internalType: "struct IReflexRouter.ExecuteParams",
        name: "executeParams",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "bytes32",
            name: "triggerPoolId",
            type: "bytes32",
          },
          {
            internalType: "uint112",
            name: "swapAmountIn",
            type: "uint112",
          },
          {
            internalType: "bool",
            name: "token0In",
            type: "bool",
          },
          {
            internalType: "address",
            name: "recipient",
            type: "address",
          },
          {
            internalType: "bytes32",
            name: "configId",
            type: "bytes32",
          },
        ],
        internalType: "struct IReflexRouter.BackrunParams[]",
        name: "backrunParams",
        type: "tuple[]",
      },
    ],
    name: "backrunedExecute",
    outputs: [
      {
        internalType: "bool",
        name: "success",
        type: "bool",
      },
      {
        internalType: "bytes",
        name: "returnData",
        type: "bytes",
      },
      {
        internalType: "uint256[]",
        name: "profits",
        type: "uint256[]",
      },
      {
        internalType: "address[]",
        name: "profitTokens",
        type: "address[]",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "getReflexAdmin",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "triggerPoolId",
        type: "bytes32",
      },
      {
        internalType: "uint112",
        name: "swapAmountIn",
        type: "uint112",
      },
      {
        internalType: "bool",
        name: "token0In",
        type: "bool",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "configId",
        type: "bytes32",
      },
    ],
    name: "triggerBackrun",
    outputs: [
      {
        internalType: "uint256",
        name: "profit",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "profitToken",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IReflexRouter__factory {
  static readonly abi = _abi;
  static createInterface(): IReflexRouterInterface {
    return new Interface(_abi) as IReflexRouterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IReflexRouter {
    return new Contract(address, _abi, runner) as unknown as IReflexRouter;
  }
}
