/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  PoolMock,
  PoolMockInterface,
} from "../../../contracts/test/PoolMock";

const _abi = [
  {
    inputs: [
      {
        internalType: "int24",
        name: "targetTick",
        type: "int24",
      },
      {
        internalType: "bool",
        name: "zeroToOne",
        type: "bool",
      },
    ],
    name: "crossTo",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "plugin",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newPlugin",
        type: "address",
      },
    ],
    name: "setPlugin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newVirtualPool",
        type: "address",
      },
    ],
    name: "setVirtualPool",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "virtualPool",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506102fd806100206000396000f3fe608060405234801561001057600080fd5b50600436106100675760003560e01c8063838b494011610050578063838b4940146100d9578063cc1f97cf14610130578063ef01df4f1461018557600080fd5b806334d335901461006c5780634ad1458314610094575b600080fd5b61007f61007a36600461025e565b6101a5565b60405190151581526020015b60405180910390f35b6001546100b49073ffffffffffffffffffffffffffffffffffffffff1681565b60405173ffffffffffffffffffffffffffffffffffffffff909116815260200161008b565b61012e6100e736600461029d565b600180547fffffffffffffffffffffffff00000000000000000000000000000000000000001673ffffffffffffffffffffffffffffffffffffffff92909216919091179055565b005b61012e61013e36600461029d565b600080547fffffffffffffffffffffffff00000000000000000000000000000000000000001673ffffffffffffffffffffffffffffffffffffffff92909216919091179055565b6000546100b49073ffffffffffffffffffffffffffffffffffffffff1681565b6001546040517f34d33590000000000000000000000000000000000000000000000000000000008152600284900b6004820152821515602482015260009173ffffffffffffffffffffffffffffffffffffffff16906334d33590906044016020604051808303816000875af1158015610222573d6000803e3d6000fd5b505050506040513d601f19601f8201168201806040525081019061024691906102d3565b9392505050565b801515811461025b57600080fd5b50565b6000806040838503121561027157600080fd5b82358060020b811461028257600080fd5b915060208301356102928161024d565b809150509250929050565b6000602082840312156102af57600080fd5b813573ffffffffffffffffffffffffffffffffffffffff8116811461024657600080fd5b6000602082840312156102e557600080fd5b81516102468161024d56fea164736f6c6343000814000a";

type PoolMockConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PoolMockConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PoolMock__factory extends ContractFactory {
  constructor(...args: PoolMockConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      PoolMock & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): PoolMock__factory {
    return super.connect(runner) as PoolMock__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PoolMockInterface {
    return new Interface(_abi) as PoolMockInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): PoolMock {
    return new Contract(address, _abi, runner) as unknown as PoolMock;
  }
}
