/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAlgebraMintCallback } from "./IAlgebraMintCallback";
export type { IAlgebraSwapCallback } from "./IAlgebraSwapCallback";
