/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPluginV3Deployer,
  IPluginV3DeployerInterface,
} from "../../../contracts/interfaces/IPluginV3Deployer";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
      {
        internalType: "address",
        name: "algebraFactory",
        type: "address",
      },
      {
        internalType: "address",
        name: "pluginFactory",
        type: "address",
      },
      {
        components: [
          {
            internalType: "uint16",
            name: "alpha1",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "alpha2",
            type: "uint16",
          },
          {
            internalType: "uint32",
            name: "beta1",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "beta2",
            type: "uint32",
          },
          {
            internalType: "uint16",
            name: "gamma1",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "gamma2",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "baseFee",
            type: "uint16",
          },
        ],
        internalType: "struct AlgebraFeeConfiguration",
        name: "defaultFeeConfiguration",
        type: "tuple",
      },
      {
        internalType: "address",
        name: "reflexRouter",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "reflexConfigId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "feeDiscountRegistry",
        type: "address",
      },
    ],
    name: "deployPlugin",
    outputs: [
      {
        internalType: "address",
        name: "plugin",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPluginV3Deployer__factory {
  static readonly abi = _abi;
  static createInterface(): IPluginV3DeployerInterface {
    return new Interface(_abi) as IPluginV3DeployerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPluginV3Deployer {
    return new Contract(address, _abi, runner) as unknown as IPluginV3Deployer;
  }
}
