/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace NonfungibleTokenPositionDescriptor {
  export type TokenRatioSortDataStruct = {
    tokenAddress: AddressLike;
    tokenRatioSortOrder: BigNumberish;
  };

  export type TokenRatioSortDataStructOutput = [
    tokenAddress: string,
    tokenRatioSortOrder: bigint
  ] & { tokenAddress: string; tokenRatioSortOrder: bigint };
}

export interface NonfungibleTokenPositionDescriptorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "WNativeToken"
      | "cachedThis"
      | "flipRatio"
      | "nativeCurrencySymbol"
      | "tokenRatioPriority"
      | "tokenURI"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "WNativeToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cachedThis",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "flipRatio",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nativeCurrencySymbol",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenRatioPriority",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "WNativeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cachedThis", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "flipRatio", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nativeCurrencySymbol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenRatioPriority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
}

export interface NonfungibleTokenPositionDescriptor extends BaseContract {
  connect(runner?: ContractRunner | null): NonfungibleTokenPositionDescriptor;
  waitForDeployment(): Promise<this>;

  interface: NonfungibleTokenPositionDescriptorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  WNativeToken: TypedContractMethod<[], [string], "view">;

  cachedThis: TypedContractMethod<[], [string], "view">;

  flipRatio: TypedContractMethod<
    [token0: AddressLike, token1: AddressLike],
    [boolean],
    "view"
  >;

  nativeCurrencySymbol: TypedContractMethod<[], [string], "view">;

  tokenRatioPriority: TypedContractMethod<
    [token: AddressLike],
    [bigint],
    "view"
  >;

  tokenURI: TypedContractMethod<
    [positionManager: AddressLike, tokenId: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "WNativeToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cachedThis"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "flipRatio"
  ): TypedContractMethod<
    [token0: AddressLike, token1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nativeCurrencySymbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenRatioPriority"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<
    [positionManager: AddressLike, tokenId: BigNumberish],
    [string],
    "view"
  >;

  filters: {};
}
