/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export type AlgebraFeeConfigurationStruct = {
  alpha1: BigNumberish;
  alpha2: BigNumberish;
  beta1: BigNumberish;
  beta2: BigNumberish;
  gamma1: BigNumberish;
  gamma2: BigNumberish;
  baseFee: BigNumberish;
};

export type AlgebraFeeConfigurationStructOutput = [
  alpha1: bigint,
  alpha2: bigint,
  beta1: bigint,
  beta2: bigint,
  gamma1: bigint,
  gamma2: bigint,
  baseFee: bigint
] & {
  alpha1: bigint;
  alpha2: bigint;
  beta1: bigint;
  beta2: bigint;
  gamma1: bigint;
  gamma2: bigint;
  baseFee: bigint;
};

export interface IDynamicFeeManagerInterface extends Interface {
  getFunction(
    nameOrSignature: "changeFeeConfiguration" | "feeConfig" | "getCurrentFee"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "FeeConfiguration"): EventFragment;

  encodeFunctionData(
    functionFragment: "changeFeeConfiguration",
    values: [AlgebraFeeConfigurationStruct]
  ): string;
  encodeFunctionData(functionFragment: "feeConfig", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCurrentFee",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "changeFeeConfiguration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeConfig", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentFee",
    data: BytesLike
  ): Result;
}

export namespace FeeConfigurationEvent {
  export type InputTuple = [feeConfig: AlgebraFeeConfigurationStruct];
  export type OutputTuple = [feeConfig: AlgebraFeeConfigurationStructOutput];
  export interface OutputObject {
    feeConfig: AlgebraFeeConfigurationStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IDynamicFeeManager extends BaseContract {
  connect(runner?: ContractRunner | null): IDynamicFeeManager;
  waitForDeployment(): Promise<this>;

  interface: IDynamicFeeManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  changeFeeConfiguration: TypedContractMethod<
    [feeConfig: AlgebraFeeConfigurationStruct],
    [void],
    "nonpayable"
  >;

  feeConfig: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        alpha1: bigint;
        alpha2: bigint;
        beta1: bigint;
        beta2: bigint;
        gamma1: bigint;
        gamma2: bigint;
        baseFee: bigint;
      }
    ],
    "view"
  >;

  getCurrentFee: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "changeFeeConfiguration"
  ): TypedContractMethod<
    [feeConfig: AlgebraFeeConfigurationStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeConfig"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        alpha1: bigint;
        alpha2: bigint;
        beta1: bigint;
        beta2: bigint;
        gamma1: bigint;
        gamma2: bigint;
        baseFee: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentFee"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "FeeConfiguration"
  ): TypedContractEvent<
    FeeConfigurationEvent.InputTuple,
    FeeConfigurationEvent.OutputTuple,
    FeeConfigurationEvent.OutputObject
  >;

  filters: {
    "FeeConfiguration(tuple)": TypedContractEvent<
      FeeConfigurationEvent.InputTuple,
      FeeConfigurationEvent.OutputTuple,
      FeeConfigurationEvent.OutputObject
    >;
    FeeConfiguration: TypedContractEvent<
      FeeConfigurationEvent.InputTuple,
      FeeConfigurationEvent.OutputTuple,
      FeeConfigurationEvent.OutputObject
    >;
  };
}
