/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ISecurityPluginInterface extends Interface {
  getFunction(
    nameOrSignature: "getSecurityRegistry" | "setSecurityRegistry"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "SecurityRegistry"): EventFragment;

  encodeFunctionData(
    functionFragment: "getSecurityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setSecurityRegistry",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getSecurityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSecurityRegistry",
    data: BytesLike
  ): Result;
}

export namespace SecurityRegistryEvent {
  export type InputTuple = [registry: AddressLike];
  export type OutputTuple = [registry: string];
  export interface OutputObject {
    registry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ISecurityPlugin extends BaseContract {
  connect(runner?: ContractRunner | null): ISecurityPlugin;
  waitForDeployment(): Promise<this>;

  interface: ISecurityPluginInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getSecurityRegistry: TypedContractMethod<[], [string], "view">;

  setSecurityRegistry: TypedContractMethod<
    [registry: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getSecurityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setSecurityRegistry"
  ): TypedContractMethod<[registry: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "SecurityRegistry"
  ): TypedContractEvent<
    SecurityRegistryEvent.InputTuple,
    SecurityRegistryEvent.OutputTuple,
    SecurityRegistryEvent.OutputObject
  >;

  filters: {
    "SecurityRegistry(address)": TypedContractEvent<
      SecurityRegistryEvent.InputTuple,
      SecurityRegistryEvent.OutputTuple,
      SecurityRegistryEvent.OutputObject
    >;
    SecurityRegistry: TypedContractEvent<
      SecurityRegistryEvent.InputTuple,
      SecurityRegistryEvent.OutputTuple,
      SecurityRegistryEvent.OutputObject
    >;
  };
}
