/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ISlidingFeePluginInterface extends Interface {
  getFunction(
    nameOrSignature: "setBaseFee" | "setPriceChangeFactor"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "BaseFee" | "PriceChangeFactor"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "setBaseFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPriceChangeFactor",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "setBaseFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPriceChangeFactor",
    data: BytesLike
  ): Result;
}

export namespace BaseFeeEvent {
  export type InputTuple = [baseFee: BigNumberish];
  export type OutputTuple = [baseFee: bigint];
  export interface OutputObject {
    baseFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceChangeFactorEvent {
  export type InputTuple = [priceChangeFactor: BigNumberish];
  export type OutputTuple = [priceChangeFactor: bigint];
  export interface OutputObject {
    priceChangeFactor: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ISlidingFeePlugin extends BaseContract {
  connect(runner?: ContractRunner | null): ISlidingFeePlugin;
  waitForDeployment(): Promise<this>;

  interface: ISlidingFeePluginInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  setBaseFee: TypedContractMethod<
    [newBaseFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPriceChangeFactor: TypedContractMethod<
    [newPriceChangeFactor: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "setBaseFee"
  ): TypedContractMethod<[newBaseFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPriceChangeFactor"
  ): TypedContractMethod<
    [newPriceChangeFactor: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BaseFee"
  ): TypedContractEvent<
    BaseFeeEvent.InputTuple,
    BaseFeeEvent.OutputTuple,
    BaseFeeEvent.OutputObject
  >;
  getEvent(
    key: "PriceChangeFactor"
  ): TypedContractEvent<
    PriceChangeFactorEvent.InputTuple,
    PriceChangeFactorEvent.OutputTuple,
    PriceChangeFactorEvent.OutputObject
  >;

  filters: {
    "BaseFee(uint16)": TypedContractEvent<
      BaseFeeEvent.InputTuple,
      BaseFeeEvent.OutputTuple,
      BaseFeeEvent.OutputObject
    >;
    BaseFee: TypedContractEvent<
      BaseFeeEvent.InputTuple,
      BaseFeeEvent.OutputTuple,
      BaseFeeEvent.OutputObject
    >;

    "PriceChangeFactor(uint256)": TypedContractEvent<
      PriceChangeFactorEvent.InputTuple,
      PriceChangeFactorEvent.OutputTuple,
      PriceChangeFactorEvent.OutputObject
    >;
    PriceChangeFactor: TypedContractEvent<
      PriceChangeFactorEvent.InputTuple,
      PriceChangeFactorEvent.OutputTuple,
      PriceChangeFactorEvent.OutputObject
    >;
  };
}
