/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IVolatilityOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getSingleTimepoint"
      | "getTimepoints"
      | "initialize"
      | "isInitialized"
      | "lastTimepointTimestamp"
      | "prepayTimepointsStorageSlots"
      | "timepointIndex"
      | "timepoints"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getSingleTimepoint",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTimepoints",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isInitialized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastTimepointTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "prepayTimepointsStorageSlots",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "timepointIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "timepoints",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getSingleTimepoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTimepoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastTimepointTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "prepayTimepointsStorageSlots",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timepointIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "timepoints", data: BytesLike): Result;
}

export interface IVolatilityOracle extends BaseContract {
  connect(runner?: ContractRunner | null): IVolatilityOracle;
  waitForDeployment(): Promise<this>;

  interface: IVolatilityOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getSingleTimepoint: TypedContractMethod<
    [secondsAgo: BigNumberish],
    [
      [bigint, bigint] & {
        tickCumulative: bigint;
        volatilityCumulative: bigint;
      }
    ],
    "view"
  >;

  getTimepoints: TypedContractMethod<
    [secondsAgos: BigNumberish[]],
    [
      [bigint[], bigint[]] & {
        tickCumulatives: bigint[];
        volatilityCumulatives: bigint[];
      }
    ],
    "view"
  >;

  initialize: TypedContractMethod<[], [void], "nonpayable">;

  isInitialized: TypedContractMethod<[], [boolean], "view">;

  lastTimepointTimestamp: TypedContractMethod<[], [bigint], "view">;

  prepayTimepointsStorageSlots: TypedContractMethod<
    [startIndex: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  timepointIndex: TypedContractMethod<[], [bigint], "view">;

  timepoints: TypedContractMethod<
    [index: BigNumberish],
    [
      [boolean, bigint, bigint, bigint, bigint, bigint, bigint] & {
        initialized: boolean;
        blockTimestamp: bigint;
        tickCumulative: bigint;
        volatilityCumulative: bigint;
        tick: bigint;
        averageTick: bigint;
        windowStartIndex: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getSingleTimepoint"
  ): TypedContractMethod<
    [secondsAgo: BigNumberish],
    [
      [bigint, bigint] & {
        tickCumulative: bigint;
        volatilityCumulative: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTimepoints"
  ): TypedContractMethod<
    [secondsAgos: BigNumberish[]],
    [
      [bigint[], bigint[]] & {
        tickCumulatives: bigint[];
        volatilityCumulatives: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isInitialized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastTimepointTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "prepayTimepointsStorageSlots"
  ): TypedContractMethod<
    [startIndex: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "timepointIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "timepoints"
  ): TypedContractMethod<
    [index: BigNumberish],
    [
      [boolean, bigint, bigint, bigint, bigint, bigint, bigint] & {
        initialized: boolean;
        blockTimestamp: bigint;
        tickCumulative: bigint;
        volatilityCumulative: bigint;
        tick: bigint;
        averageTick: bigint;
        windowStartIndex: bigint;
      }
    ],
    "view"
  >;

  filters: {};
}
