/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface EternalVirtualPoolEchidnaTestInterface extends Interface {
  getFunction(
    nameOrSignature: "applyLiquidityDeltaToPosition" | "crossTo"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "applyLiquidityDeltaToPosition",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "crossTo",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "applyLiquidityDeltaToPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "crossTo", data: BytesLike): Result;
}

export interface EternalVirtualPoolEchidnaTest extends BaseContract {
  connect(runner?: ContractRunner | null): EternalVirtualPoolEchidnaTest;
  waitForDeployment(): Promise<this>;

  interface: EternalVirtualPoolEchidnaTestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  applyLiquidityDeltaToPosition: TypedContractMethod<
    [
      bottomTick: BigNumberish,
      topTick: BigNumberish,
      liquidityDelta: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  crossTo: TypedContractMethod<
    [targetTick: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "applyLiquidityDeltaToPosition"
  ): TypedContractMethod<
    [
      bottomTick: BigNumberish,
      topTick: BigNumberish,
      liquidityDelta: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "crossTo"
  ): TypedContractMethod<[targetTick: BigNumberish], [void], "nonpayable">;

  filters: {};
}
