/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MockPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "burn"
      | "collect"
      | "communityVault"
      | "fee"
      | "flash"
      | "getCommunityFeePending"
      | "getPluginFeePending"
      | "getReserves"
      | "globalState"
      | "initialize"
      | "isUnlocked"
      | "lastFeeTransferTimestamp"
      | "liquidity"
      | "mint"
      | "nextTickGlobal"
      | "overrideFee"
      | "plugin"
      | "pluginFee"
      | "positions"
      | "prevTickGlobal"
      | "safelyGetStateOfAMM"
      | "setCommunityFee"
      | "setCommunityVault"
      | "setFee"
      | "setPlugin"
      | "setPluginConfig"
      | "setTickSpacing"
      | "skim"
      | "swap"
      | "swapToTick"
      | "swapWithPaymentInAdvance"
      | "sync"
      | "tickSpacing"
      | "tickTable"
      | "tickTreeRoot"
      | "tickTreeSecondLayer"
      | "ticks"
      | "totalFeeGrowth0Token"
      | "totalFeeGrowth1Token"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "burn",
    values: [BigNumberish, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "collect",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "communityVault",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "fee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "flash",
    values: [AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCommunityFeePending",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPluginFeePending",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReserves",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "globalState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isUnlocked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastFeeTransferTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "liquidity", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "nextTickGlobal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "overrideFee",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "plugin", values?: undefined): string;
  encodeFunctionData(functionFragment: "pluginFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "positions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "prevTickGlobal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "safelyGetStateOfAMM",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setCommunityFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCommunityVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlugin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPluginConfig",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTickSpacing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "skim", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "swap",
    values: [AddressLike, boolean, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swapToTick",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapWithPaymentInAdvance",
    values: [
      AddressLike,
      AddressLike,
      boolean,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "sync", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tickSpacing",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tickTable",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tickTreeRoot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tickTreeSecondLayer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "ticks", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "totalFeeGrowth0Token",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalFeeGrowth1Token",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "collect", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "communityVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "flash", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCommunityFeePending",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPluginFeePending",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isUnlocked", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastFeeTransferTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "liquidity", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextTickGlobal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "overrideFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "plugin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pluginFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "positions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "prevTickGlobal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safelyGetStateOfAMM",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCommunityFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCommunityVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setPlugin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPluginConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTickSpacing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "skim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swapToTick", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapWithPaymentInAdvance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sync", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tickSpacing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tickTable", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tickTreeRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tickTreeSecondLayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ticks", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalFeeGrowth0Token",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFeeGrowth1Token",
    data: BytesLike
  ): Result;
}

export interface MockPool extends BaseContract {
  connect(runner?: ContractRunner | null): MockPool;
  waitForDeployment(): Promise<this>;

  interface: MockPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  burn: TypedContractMethod<
    [
      bottomTick: BigNumberish,
      topTick: BigNumberish,
      liquidityDesired: BigNumberish,
      data: BytesLike
    ],
    [[bigint, bigint]],
    "nonpayable"
  >;

  collect: TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: BigNumberish,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BigNumberish
    ],
    [[bigint, bigint]],
    "view"
  >;

  communityVault: TypedContractMethod<[], [string], "view">;

  fee: TypedContractMethod<[], [bigint], "view">;

  flash: TypedContractMethod<
    [
      recipient: AddressLike,
      amount0: BigNumberish,
      amount1: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getCommunityFeePending: TypedContractMethod<[], [[bigint, bigint]], "view">;

  getPluginFeePending: TypedContractMethod<[], [[bigint, bigint]], "view">;

  getReserves: TypedContractMethod<[], [[bigint, bigint]], "view">;

  globalState: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        price: bigint;
        tick: bigint;
        fee: bigint;
        pluginConfig: bigint;
        communityFee: bigint;
        unlocked: boolean;
      }
    ],
    "view"
  >;

  initialize: TypedContractMethod<
    [initialPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  isUnlocked: TypedContractMethod<[], [boolean], "view">;

  lastFeeTransferTimestamp: TypedContractMethod<[], [bigint], "view">;

  liquidity: TypedContractMethod<[], [bigint], "view">;

  mint: TypedContractMethod<
    [
      arg0: AddressLike,
      recipient: AddressLike,
      bottomTick: BigNumberish,
      topTick: BigNumberish,
      liquidityDesired: BigNumberish,
      data: BytesLike
    ],
    [[bigint, bigint, bigint]],
    "nonpayable"
  >;

  nextTickGlobal: TypedContractMethod<[], [bigint], "view">;

  overrideFee: TypedContractMethod<[], [bigint], "view">;

  plugin: TypedContractMethod<[], [string], "view">;

  pluginFee: TypedContractMethod<[], [bigint], "view">;

  positions: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        liquidity: bigint;
        innerFeeGrowth0Token: bigint;
        innerFeeGrowth1Token: bigint;
        fees0: bigint;
        fees1: bigint;
      }
    ],
    "view"
  >;

  prevTickGlobal: TypedContractMethod<[], [bigint], "view">;

  safelyGetStateOfAMM: TypedContractMethod<
    [],
    [[bigint, bigint, bigint, bigint, bigint, bigint, bigint]],
    "view"
  >;

  setCommunityFee: TypedContractMethod<
    [newCommunityFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setCommunityVault: TypedContractMethod<
    [newCommunityVault: AddressLike],
    [void],
    "nonpayable"
  >;

  setFee: TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;

  setPlugin: TypedContractMethod<
    [newPluginAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setPluginConfig: TypedContractMethod<
    [newConfig: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTickSpacing: TypedContractMethod<
    [newTickSpacing: BigNumberish],
    [void],
    "nonpayable"
  >;

  skim: TypedContractMethod<[], [void], "view">;

  swap: TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: boolean,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike
    ],
    [[bigint, bigint]],
    "view"
  >;

  swapToTick: TypedContractMethod<
    [targetTick: BigNumberish],
    [void],
    "nonpayable"
  >;

  swapWithPaymentInAdvance: TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: boolean,
      arg3: BigNumberish,
      arg4: BigNumberish,
      arg5: BytesLike
    ],
    [[bigint, bigint]],
    "view"
  >;

  sync: TypedContractMethod<[], [void], "view">;

  tickSpacing: TypedContractMethod<[], [bigint], "view">;

  tickTable: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  tickTreeRoot: TypedContractMethod<[], [bigint], "view">;

  tickTreeSecondLayer: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  ticks: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        liquidityTotal: bigint;
        liquidityDelta: bigint;
        prevTick: bigint;
        nextTick: bigint;
        outerFeeGrowth0Token: bigint;
        outerFeeGrowth1Token: bigint;
      }
    ],
    "view"
  >;

  totalFeeGrowth0Token: TypedContractMethod<[], [bigint], "view">;

  totalFeeGrowth1Token: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "burn"
  ): TypedContractMethod<
    [
      bottomTick: BigNumberish,
      topTick: BigNumberish,
      liquidityDesired: BigNumberish,
      data: BytesLike
    ],
    [[bigint, bigint]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "collect"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: BigNumberish,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BigNumberish
    ],
    [[bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "communityVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "flash"
  ): TypedContractMethod<
    [
      recipient: AddressLike,
      amount0: BigNumberish,
      amount1: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCommunityFeePending"
  ): TypedContractMethod<[], [[bigint, bigint]], "view">;
  getFunction(
    nameOrSignature: "getPluginFeePending"
  ): TypedContractMethod<[], [[bigint, bigint]], "view">;
  getFunction(
    nameOrSignature: "getReserves"
  ): TypedContractMethod<[], [[bigint, bigint]], "view">;
  getFunction(
    nameOrSignature: "globalState"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        price: bigint;
        tick: bigint;
        fee: bigint;
        pluginConfig: bigint;
        communityFee: bigint;
        unlocked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[initialPrice: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isUnlocked"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastFeeTransferTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "liquidity"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "mint"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      recipient: AddressLike,
      bottomTick: BigNumberish,
      topTick: BigNumberish,
      liquidityDesired: BigNumberish,
      data: BytesLike
    ],
    [[bigint, bigint, bigint]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextTickGlobal"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "overrideFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "plugin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pluginFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "positions"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        liquidity: bigint;
        innerFeeGrowth0Token: bigint;
        innerFeeGrowth1Token: bigint;
        fees0: bigint;
        fees1: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "prevTickGlobal"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "safelyGetStateOfAMM"
  ): TypedContractMethod<
    [],
    [[bigint, bigint, bigint, bigint, bigint, bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "setCommunityFee"
  ): TypedContractMethod<[newCommunityFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setCommunityVault"
  ): TypedContractMethod<
    [newCommunityVault: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFee"
  ): TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlugin"
  ): TypedContractMethod<[newPluginAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPluginConfig"
  ): TypedContractMethod<[newConfig: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTickSpacing"
  ): TypedContractMethod<[newTickSpacing: BigNumberish], [void], "nonpayable">;
  getFunction(nameOrSignature: "skim"): TypedContractMethod<[], [void], "view">;
  getFunction(
    nameOrSignature: "swap"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: boolean,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike
    ],
    [[bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "swapToTick"
  ): TypedContractMethod<[targetTick: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "swapWithPaymentInAdvance"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: boolean,
      arg3: BigNumberish,
      arg4: BigNumberish,
      arg5: BytesLike
    ],
    [[bigint, bigint]],
    "view"
  >;
  getFunction(nameOrSignature: "sync"): TypedContractMethod<[], [void], "view">;
  getFunction(
    nameOrSignature: "tickSpacing"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tickTable"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "tickTreeRoot"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tickTreeSecondLayer"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "ticks"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        liquidityTotal: bigint;
        liquidityDelta: bigint;
        prevTick: bigint;
        nextTick: bigint;
        outerFeeGrowth0Token: bigint;
        outerFeeGrowth1Token: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalFeeGrowth0Token"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalFeeGrowth1Token"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
