/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type AlgebraFeeConfigurationStruct = {
  alpha1: BigNumberish;
  alpha2: BigNumberish;
  beta1: BigNumberish;
  beta2: BigNumberish;
  gamma1: BigNumberish;
  gamma2: BigNumberish;
  baseFee: BigNumberish;
};

export type AlgebraFeeConfigurationStructOutput = [
  alpha1: bigint,
  alpha2: bigint,
  beta1: bigint,
  beta2: bigint,
  gamma1: bigint,
  gamma2: bigint,
  baseFee: bigint
] & {
  alpha1: bigint;
  alpha2: bigint;
  beta1: bigint;
  beta2: bigint;
  gamma1: bigint;
  gamma2: bigint;
  baseFee: bigint;
};

export declare namespace VolatilityOracleTest {
  export type UpdateParamsStruct = {
    advanceTimeBy: BigNumberish;
    tick: BigNumberish;
  };

  export type UpdateParamsStructOutput = [
    advanceTimeBy: bigint,
    tick: bigint
  ] & { advanceTimeBy: bigint; tick: bigint };

  export type InitializeParamsStruct = {
    time: BigNumberish;
    tick: BigNumberish;
  };

  export type InitializeParamsStructOutput = [time: bigint, tick: bigint] & {
    time: bigint;
    tick: bigint;
  };
}

export declare namespace VolatilityOracle {
  export type TimepointStruct = {
    initialized: boolean;
    blockTimestamp: BigNumberish;
    tickCumulative: BigNumberish;
    volatilityCumulative: BigNumberish;
    tick: BigNumberish;
    averageTick: BigNumberish;
    windowStartIndex: BigNumberish;
  };

  export type TimepointStructOutput = [
    initialized: boolean,
    blockTimestamp: bigint,
    tickCumulative: bigint,
    volatilityCumulative: bigint,
    tick: bigint,
    averageTick: bigint,
    windowStartIndex: bigint
  ] & {
    initialized: boolean;
    blockTimestamp: bigint;
    tickCumulative: bigint;
    volatilityCumulative: bigint;
    tick: bigint;
    averageTick: bigint;
    windowStartIndex: bigint;
  };
}

export interface SimulationAdaptiveFeeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "advanceTime"
      | "batchUpdate"
      | "batchUpdateFast"
      | "batchUpdateFixedTimedelta"
      | "changeFeeConfiguration"
      | "getAverageTick"
      | "getAverageVolatility"
      | "getFee"
      | "getGasCostOfGetPoints"
      | "getOldestIndex"
      | "getTickCumulativeAt"
      | "getTimepoints"
      | "index"
      | "init"
      | "initialize"
      | "setState"
      | "setStep"
      | "tick"
      | "time"
      | "timepoints"
      | "update"
      | "volatilityOnRange"
      | "window"
      | "writeTimepointDirectly"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "advanceTime",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batchUpdate",
    values: [VolatilityOracleTest.UpdateParamsStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchUpdateFast",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batchUpdateFixedTimedelta",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "changeFeeConfiguration",
    values: [AlgebraFeeConfigurationStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getAverageTick",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAverageVolatility",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getGasCostOfGetPoints",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getOldestIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTickCumulativeAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTimepoints",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "index", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "init",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [VolatilityOracleTest.InitializeParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setState",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setStep",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "tick", values?: undefined): string;
  encodeFunctionData(functionFragment: "time", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "timepoints",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "update",
    values: [VolatilityOracleTest.UpdateParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "volatilityOnRange",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "window", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "writeTimepointDirectly",
    values: [BigNumberish, VolatilityOracle.TimepointStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "advanceTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchUpdateFast",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchUpdateFixedTimedelta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeFeeConfiguration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAverageTick",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAverageVolatility",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getGasCostOfGetPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOldestIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTickCumulativeAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTimepoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "index", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setState", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setStep", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tick", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "time", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "timepoints", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "update", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "volatilityOnRange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "window", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "writeTimepointDirectly",
    data: BytesLike
  ): Result;
}

export interface SimulationAdaptiveFee extends BaseContract {
  connect(runner?: ContractRunner | null): SimulationAdaptiveFee;
  waitForDeployment(): Promise<this>;

  interface: SimulationAdaptiveFeeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  advanceTime: TypedContractMethod<[by: BigNumberish], [void], "nonpayable">;

  batchUpdate: TypedContractMethod<
    [params: VolatilityOracleTest.UpdateParamsStruct[]],
    [void],
    "nonpayable"
  >;

  batchUpdateFast: TypedContractMethod<
    [length: BigNumberish],
    [void],
    "nonpayable"
  >;

  batchUpdateFixedTimedelta: TypedContractMethod<
    [length: BigNumberish],
    [void],
    "nonpayable"
  >;

  changeFeeConfiguration: TypedContractMethod<
    [_config: AlgebraFeeConfigurationStruct],
    [void],
    "nonpayable"
  >;

  getAverageTick: TypedContractMethod<[], [bigint], "view">;

  getAverageVolatility: TypedContractMethod<[], [bigint], "view">;

  getFee: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        fee: bigint;
        volatilityAverage: bigint;
        averageTick: bigint;
      }
    ],
    "view"
  >;

  getGasCostOfGetPoints: TypedContractMethod<
    [secondsAgos: BigNumberish[]],
    [bigint],
    "view"
  >;

  getOldestIndex: TypedContractMethod<[], [bigint], "view">;

  getTickCumulativeAt: TypedContractMethod<
    [secondsAgo: BigNumberish],
    [bigint],
    "view"
  >;

  getTimepoints: TypedContractMethod<
    [secondsAgos: BigNumberish[]],
    [
      [bigint[], bigint[]] & {
        tickCumulatives: bigint[];
        volatilityCumulatives: bigint[];
      }
    ],
    "view"
  >;

  index: TypedContractMethod<[], [bigint], "view">;

  init: TypedContractMethod<
    [initTick: BigNumberish, initTime: BigNumberish],
    [void],
    "nonpayable"
  >;

  initialize: TypedContractMethod<
    [params: VolatilityOracleTest.InitializeParamsStruct],
    [void],
    "nonpayable"
  >;

  setState: TypedContractMethod<
    [_time: BigNumberish, _index: BigNumberish],
    [void],
    "nonpayable"
  >;

  setStep: TypedContractMethod<[newStep: BigNumberish], [void], "nonpayable">;

  tick: TypedContractMethod<[], [bigint], "view">;

  time: TypedContractMethod<[], [bigint], "view">;

  timepoints: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [boolean, bigint, bigint, bigint, bigint, bigint, bigint] & {
        initialized: boolean;
        blockTimestamp: bigint;
        tickCumulative: bigint;
        volatilityCumulative: bigint;
        tick: bigint;
        averageTick: bigint;
        windowStartIndex: bigint;
      }
    ],
    "view"
  >;

  update: TypedContractMethod<
    [params: VolatilityOracleTest.UpdateParamsStruct],
    [void],
    "nonpayable"
  >;

  volatilityOnRange: TypedContractMethod<
    [
      dt: BigNumberish,
      tick0: BigNumberish,
      tick1: BigNumberish,
      avgTick0: BigNumberish,
      avgTick1: BigNumberish
    ],
    [bigint],
    "view"
  >;

  window: TypedContractMethod<[], [bigint], "view">;

  writeTimepointDirectly: TypedContractMethod<
    [_index: BigNumberish, timepoint: VolatilityOracle.TimepointStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "advanceTime"
  ): TypedContractMethod<[by: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "batchUpdate"
  ): TypedContractMethod<
    [params: VolatilityOracleTest.UpdateParamsStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchUpdateFast"
  ): TypedContractMethod<[length: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "batchUpdateFixedTimedelta"
  ): TypedContractMethod<[length: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "changeFeeConfiguration"
  ): TypedContractMethod<
    [_config: AlgebraFeeConfigurationStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAverageTick"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAverageVolatility"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getFee"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        fee: bigint;
        volatilityAverage: bigint;
        averageTick: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGasCostOfGetPoints"
  ): TypedContractMethod<[secondsAgos: BigNumberish[]], [bigint], "view">;
  getFunction(
    nameOrSignature: "getOldestIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTickCumulativeAt"
  ): TypedContractMethod<[secondsAgo: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTimepoints"
  ): TypedContractMethod<
    [secondsAgos: BigNumberish[]],
    [
      [bigint[], bigint[]] & {
        tickCumulatives: bigint[];
        volatilityCumulatives: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "index"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "init"
  ): TypedContractMethod<
    [initTick: BigNumberish, initTime: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [params: VolatilityOracleTest.InitializeParamsStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setState"
  ): TypedContractMethod<
    [_time: BigNumberish, _index: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setStep"
  ): TypedContractMethod<[newStep: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tick"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "time"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "timepoints"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [boolean, bigint, bigint, bigint, bigint, bigint, bigint] & {
        initialized: boolean;
        blockTimestamp: bigint;
        tickCumulative: bigint;
        volatilityCumulative: bigint;
        tick: bigint;
        averageTick: bigint;
        windowStartIndex: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "update"
  ): TypedContractMethod<
    [params: VolatilityOracleTest.UpdateParamsStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "volatilityOnRange"
  ): TypedContractMethod<
    [
      dt: BigNumberish,
      tick0: BigNumberish,
      tick1: BigNumberish,
      avgTick0: BigNumberish,
      avgTick1: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "window"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "writeTimepointDirectly"
  ): TypedContractMethod<
    [_index: BigNumberish, timepoint: VolatilityOracle.TimepointStruct],
    [void],
    "nonpayable"
  >;

  filters: {};
}
