/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface MockPositionFollowerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "applyLiquidityDelta"
      | "enterToFarming"
      | "exitFromFarming"
      | "setFailForToken"
      | "wasCalled"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "applyLiquidityDelta",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "enterToFarming",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "exitFromFarming",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFailForToken",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "wasCalled", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "applyLiquidityDelta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enterToFarming",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "exitFromFarming",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFailForToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "wasCalled", data: BytesLike): Result;
}

export interface MockPositionFollower extends BaseContract {
  connect(runner?: ContractRunner | null): MockPositionFollower;
  waitForDeployment(): Promise<this>;

  interface: MockPositionFollowerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  applyLiquidityDelta: TypedContractMethod<
    [tokenId: BigNumberish, arg1: BigNumberish],
    [void],
    "nonpayable"
  >;

  enterToFarming: TypedContractMethod<
    [posManager: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  exitFromFarming: TypedContractMethod<
    [posManager: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFailForToken: TypedContractMethod<
    [tokenId: BigNumberish, value: BigNumberish],
    [void],
    "nonpayable"
  >;

  wasCalled: TypedContractMethod<[], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "applyLiquidityDelta"
  ): TypedContractMethod<
    [tokenId: BigNumberish, arg1: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "enterToFarming"
  ): TypedContractMethod<
    [posManager: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "exitFromFarming"
  ): TypedContractMethod<
    [posManager: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFailForToken"
  ): TypedContractMethod<
    [tokenId: BigNumberish, value: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "wasCalled"
  ): TypedContractMethod<[], [boolean], "view">;

  filters: {};
}
