/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface PoolMockInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "crossTo"
      | "plugin"
      | "setPlugin"
      | "setVirtualPool"
      | "virtualPool"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "crossTo",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(functionFragment: "plugin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setPlugin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVirtualPool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "virtualPool",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "crossTo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "plugin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setPlugin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setVirtualPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "virtualPool",
    data: BytesLike
  ): Result;
}

export interface PoolMock extends BaseContract {
  connect(runner?: ContractRunner | null): PoolMock;
  waitForDeployment(): Promise<this>;

  interface: PoolMockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  crossTo: TypedContractMethod<
    [targetTick: BigNumberish, zeroToOne: boolean],
    [boolean],
    "nonpayable"
  >;

  plugin: TypedContractMethod<[], [string], "view">;

  setPlugin: TypedContractMethod<
    [newPlugin: AddressLike],
    [void],
    "nonpayable"
  >;

  setVirtualPool: TypedContractMethod<
    [newVirtualPool: AddressLike],
    [void],
    "nonpayable"
  >;

  virtualPool: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "crossTo"
  ): TypedContractMethod<
    [targetTick: BigNumberish, zeroToOne: boolean],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "plugin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setPlugin"
  ): TypedContractMethod<[newPlugin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVirtualPool"
  ): TypedContractMethod<[newVirtualPool: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "virtualPool"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
