/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface TestVirtualPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addRewards"
      | "applyLiquidityDeltaToPosition"
      | "crossTo"
      | "currentLiquidity"
      | "deactivate"
      | "deactivated"
      | "decreaseRewards"
      | "distributeRewards"
      | "farmingAddress"
      | "getInnerRewardsGrowth"
      | "globalTick"
      | "nextTick"
      | "plugin"
      | "prevTick"
      | "prevTimestamp"
      | "rewardRates"
      | "rewardReserves"
      | "setRates"
      | "ticks"
      | "totalRewardGrowth"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addRewards",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "applyLiquidityDeltaToPosition",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "crossTo",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "currentLiquidity",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deactivate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deactivated",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "decreaseRewards",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "farmingAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getInnerRewardsGrowth",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "globalTick",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "nextTick", values?: undefined): string;
  encodeFunctionData(functionFragment: "plugin", values?: undefined): string;
  encodeFunctionData(functionFragment: "prevTick", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "prevTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardRates",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardReserves",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setRates",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "ticks", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "totalRewardGrowth",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "addRewards", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "applyLiquidityDeltaToPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "crossTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deactivate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deactivated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decreaseRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "farmingAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInnerRewardsGrowth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "globalTick", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextTick", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "plugin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "prevTick", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "prevTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardRates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRates", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ticks", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalRewardGrowth",
    data: BytesLike
  ): Result;
}

export interface TestVirtualPool extends BaseContract {
  connect(runner?: ContractRunner | null): TestVirtualPool;
  waitForDeployment(): Promise<this>;

  interface: TestVirtualPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addRewards: TypedContractMethod<
    [token0Amount: BigNumberish, token1Amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  applyLiquidityDeltaToPosition: TypedContractMethod<
    [
      bottomTick: BigNumberish,
      topTick: BigNumberish,
      liquidityDelta: BigNumberish,
      currentTick: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  crossTo: TypedContractMethod<
    [targetTick: BigNumberish, zeroToOne: boolean],
    [boolean],
    "nonpayable"
  >;

  currentLiquidity: TypedContractMethod<[], [bigint], "view">;

  deactivate: TypedContractMethod<[], [void], "nonpayable">;

  deactivated: TypedContractMethod<[], [boolean], "view">;

  decreaseRewards: TypedContractMethod<
    [token0Amount: BigNumberish, token1Amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  distributeRewards: TypedContractMethod<[], [void], "nonpayable">;

  farmingAddress: TypedContractMethod<[], [string], "view">;

  getInnerRewardsGrowth: TypedContractMethod<
    [bottomTick: BigNumberish, topTick: BigNumberish],
    [
      [bigint, bigint] & {
        rewardGrowthInside0: bigint;
        rewardGrowthInside1: bigint;
      }
    ],
    "view"
  >;

  globalTick: TypedContractMethod<[], [bigint], "view">;

  nextTick: TypedContractMethod<[], [bigint], "view">;

  plugin: TypedContractMethod<[], [string], "view">;

  prevTick: TypedContractMethod<[], [bigint], "view">;

  prevTimestamp: TypedContractMethod<[], [bigint], "view">;

  rewardRates: TypedContractMethod<
    [],
    [[bigint, bigint] & { rate0: bigint; rate1: bigint }],
    "view"
  >;

  rewardReserves: TypedContractMethod<
    [],
    [[bigint, bigint] & { reserve0: bigint; reserve1: bigint }],
    "view"
  >;

  setRates: TypedContractMethod<
    [rate0: BigNumberish, rate1: BigNumberish],
    [void],
    "nonpayable"
  >;

  ticks: TypedContractMethod<
    [tickId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        liquidityTotal: bigint;
        liquidityDelta: bigint;
        prevTick: bigint;
        nextTick: bigint;
        outerFeeGrowth0Token: bigint;
        outerFeeGrowth1Token: bigint;
      }
    ],
    "view"
  >;

  totalRewardGrowth: TypedContractMethod<
    [],
    [[bigint, bigint] & { rewardGrowth0: bigint; rewardGrowth1: bigint }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addRewards"
  ): TypedContractMethod<
    [token0Amount: BigNumberish, token1Amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "applyLiquidityDeltaToPosition"
  ): TypedContractMethod<
    [
      bottomTick: BigNumberish,
      topTick: BigNumberish,
      liquidityDelta: BigNumberish,
      currentTick: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "crossTo"
  ): TypedContractMethod<
    [targetTick: BigNumberish, zeroToOne: boolean],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "currentLiquidity"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deactivate"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deactivated"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "decreaseRewards"
  ): TypedContractMethod<
    [token0Amount: BigNumberish, token1Amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "distributeRewards"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "farmingAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getInnerRewardsGrowth"
  ): TypedContractMethod<
    [bottomTick: BigNumberish, topTick: BigNumberish],
    [
      [bigint, bigint] & {
        rewardGrowthInside0: bigint;
        rewardGrowthInside1: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "globalTick"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextTick"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "plugin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "prevTick"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "prevTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "rewardRates"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { rate0: bigint; rate1: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "rewardReserves"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { reserve0: bigint; reserve1: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "setRates"
  ): TypedContractMethod<
    [rate0: BigNumberish, rate1: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ticks"
  ): TypedContractMethod<
    [tickId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        liquidityTotal: bigint;
        liquidityDelta: bigint;
        prevTick: bigint;
        nextTick: bigint;
        outerFeeGrowth0Token: bigint;
        outerFeeGrowth1Token: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalRewardGrowth"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { rewardGrowth0: bigint; rewardGrowth1: bigint }],
    "view"
  >;

  filters: {};
}
