/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type IncentiveKeyStruct = {
  rewardToken: AddressLike;
  bonusRewardToken: AddressLike;
  pool: AddressLike;
  nonce: BigNumberish;
};

export type IncentiveKeyStructOutput = [
  rewardToken: string,
  bonusRewardToken: string,
  pool: string,
  nonce: bigint
] & {
  rewardToken: string;
  bonusRewardToken: string;
  pool: string;
  nonce: bigint;
};

export interface TestIncentiveIdInterface extends Interface {
  getFunction(nameOrSignature: "compute"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "compute",
    values: [IncentiveKeyStruct]
  ): string;

  decodeFunctionResult(functionFragment: "compute", data: BytesLike): Result;
}

export interface TestIncentiveId extends BaseContract {
  connect(runner?: ContractRunner | null): TestIncentiveId;
  waitForDeployment(): Promise<this>;

  interface: TestIncentiveIdInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  compute: TypedContractMethod<[key: IncentiveKeyStruct], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "compute"
  ): TypedContractMethod<[key: IncentiveKeyStruct], [string], "view">;

  filters: {};
}
