/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FeeDiscountPlugin } from "./FeeDiscountPlugin";
export type { FeeDiscountRegistry } from "./FeeDiscountRegistry";
