/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as plugins from "./plugins";
export type { plugins };
export type { IAlgebraVirtualPool } from "./IAlgebraVirtualPool";
