/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFeeDiscountRegistry,
  IFeeDiscountRegistryInterface,
} from "../../../../../contracts/interfaces/plugins/whitelist-fee-discount/IFeeDiscountRegistry";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "pool",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "newDiscount",
        type: "uint16",
      },
    ],
    name: "FeeDiscount",
    type: "event",
  },
  {
    inputs: [],
    name: "FEE_DISCOUNT_DENOMINATOR",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "FEE_DISCOUNT_MANAGER",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "algebraFactory",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
    ],
    name: "feeDiscounts",
    outputs: [
      {
        internalType: "uint16",
        name: "feeDiscount",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "address[]",
        name: "pools",
        type: "address[]",
      },
      {
        internalType: "uint16[]",
        name: "newDiscounts",
        type: "uint16[]",
      },
    ],
    name: "setFeeDiscount",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFeeDiscountRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IFeeDiscountRegistryInterface {
    return new Interface(_abi) as IFeeDiscountRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFeeDiscountRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IFeeDiscountRegistry;
  }
}
