/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFeeDiscountPlugin,
  IFeeDiscountPluginInterface,
} from "../../../../../contracts/interfaces/plugins/whitelist-fee-discount/IFeeDiscountPlugin";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "registry",
        type: "address",
      },
    ],
    name: "FeeDiscountRegistry",
    type: "event",
  },
  {
    inputs: [],
    name: "feeDiscountRegistry",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "registry",
        type: "address",
      },
    ],
    name: "setFeeDiscountRegistry",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFeeDiscountPlugin__factory {
  static readonly abi = _abi;
  static createInterface(): IFeeDiscountPluginInterface {
    return new Interface(_abi) as IFeeDiscountPluginInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFeeDiscountPlugin {
    return new Contract(address, _abi, runner) as unknown as IFeeDiscountPlugin;
  }
}
