/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface IFeeDiscountRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FEE_DISCOUNT_DENOMINATOR"
      | "FEE_DISCOUNT_MANAGER"
      | "algebraFactory"
      | "feeDiscounts"
      | "setFeeDiscount"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "FeeDiscount"): EventFragment;

  encodeFunctionData(
    functionFragment: "FEE_DISCOUNT_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FEE_DISCOUNT_MANAGER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "algebraFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feeDiscounts",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeDiscount",
    values: [AddressLike, AddressLike[], BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "FEE_DISCOUNT_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FEE_DISCOUNT_MANAGER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "algebraFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeDiscounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeDiscount",
    data: BytesLike
  ): Result;
}

export namespace FeeDiscountEvent {
  export type InputTuple = [
    user: AddressLike,
    pool: AddressLike,
    newDiscount: BigNumberish
  ];
  export type OutputTuple = [user: string, pool: string, newDiscount: bigint];
  export interface OutputObject {
    user: string;
    pool: string;
    newDiscount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IFeeDiscountRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IFeeDiscountRegistry;
  waitForDeployment(): Promise<this>;

  interface: IFeeDiscountRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FEE_DISCOUNT_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  FEE_DISCOUNT_MANAGER: TypedContractMethod<[], [string], "view">;

  algebraFactory: TypedContractMethod<[], [string], "view">;

  feeDiscounts: TypedContractMethod<
    [user: AddressLike, pool: AddressLike],
    [bigint],
    "view"
  >;

  setFeeDiscount: TypedContractMethod<
    [user: AddressLike, pools: AddressLike[], newDiscounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FEE_DISCOUNT_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FEE_DISCOUNT_MANAGER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "algebraFactory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "feeDiscounts"
  ): TypedContractMethod<
    [user: AddressLike, pool: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "setFeeDiscount"
  ): TypedContractMethod<
    [user: AddressLike, pools: AddressLike[], newDiscounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "FeeDiscount"
  ): TypedContractEvent<
    FeeDiscountEvent.InputTuple,
    FeeDiscountEvent.OutputTuple,
    FeeDiscountEvent.OutputObject
  >;

  filters: {
    "FeeDiscount(address,address,uint16)": TypedContractEvent<
      FeeDiscountEvent.InputTuple,
      FeeDiscountEvent.OutputTuple,
      FeeDiscountEvent.OutputObject
    >;
    FeeDiscount: TypedContractEvent<
      FeeDiscountEvent.InputTuple,
      FeeDiscountEvent.OutputTuple,
      FeeDiscountEvent.OutputObject
    >;
  };
}
