/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace AlgebraInterfaceMulticall {
  export type CallStruct = {
    target: AddressLike;
    gasLimit: BigNumberish;
    callData: BytesLike;
  };

  export type CallStructOutput = [
    target: string,
    gasLimit: bigint,
    callData: string
  ] & { target: string; gasLimit: bigint; callData: string };

  export type ResultStruct = {
    success: boolean;
    gasUsed: BigNumberish;
    returnData: BytesLike;
  };

  export type ResultStructOutput = [
    success: boolean,
    gasUsed: bigint,
    returnData: string
  ] & { success: boolean; gasUsed: bigint; returnData: string };
}

export interface AlgebraInterfaceMulticallInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "gasLeft"
      | "gaslimit"
      | "getCurrentBlockTimestamp"
      | "getEthBalance"
      | "multicall"
      | "multicallWithGasLimitation"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "gasLeft", values?: undefined): string;
  encodeFunctionData(functionFragment: "gaslimit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCurrentBlockTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEthBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "multicall",
    values: [AlgebraInterfaceMulticall.CallStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "multicallWithGasLimitation",
    values: [AlgebraInterfaceMulticall.CallStruct[], BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "gasLeft", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gaslimit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentBlockTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEthBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "multicall", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "multicallWithGasLimitation",
    data: BytesLike
  ): Result;
}

export interface AlgebraInterfaceMulticall extends BaseContract {
  connect(runner?: ContractRunner | null): AlgebraInterfaceMulticall;
  waitForDeployment(): Promise<this>;

  interface: AlgebraInterfaceMulticallInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  gasLeft: TypedContractMethod<[], [bigint], "view">;

  gaslimit: TypedContractMethod<[], [bigint], "view">;

  getCurrentBlockTimestamp: TypedContractMethod<[], [bigint], "view">;

  getEthBalance: TypedContractMethod<[addr: AddressLike], [bigint], "view">;

  multicall: TypedContractMethod<
    [calls: AlgebraInterfaceMulticall.CallStruct[]],
    [
      [bigint, AlgebraInterfaceMulticall.ResultStructOutput[]] & {
        blockNumber: bigint;
        returnData: AlgebraInterfaceMulticall.ResultStructOutput[];
      }
    ],
    "nonpayable"
  >;

  multicallWithGasLimitation: TypedContractMethod<
    [calls: AlgebraInterfaceMulticall.CallStruct[], gasBuffer: BigNumberish],
    [
      [bigint, AlgebraInterfaceMulticall.ResultStructOutput[], bigint] & {
        blockNumber: bigint;
        returnData: AlgebraInterfaceMulticall.ResultStructOutput[];
        lastSuccessIndex: bigint;
      }
    ],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "gasLeft"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "gaslimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCurrentBlockTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEthBalance"
  ): TypedContractMethod<[addr: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "multicall"
  ): TypedContractMethod<
    [calls: AlgebraInterfaceMulticall.CallStruct[]],
    [
      [bigint, AlgebraInterfaceMulticall.ResultStructOutput[]] & {
        blockNumber: bigint;
        returnData: AlgebraInterfaceMulticall.ResultStructOutput[];
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "multicallWithGasLimitation"
  ): TypedContractMethod<
    [calls: AlgebraInterfaceMulticall.CallStruct[], gasBuffer: BigNumberish],
    [
      [bigint, AlgebraInterfaceMulticall.ResultStructOutput[], bigint] & {
        blockNumber: bigint;
        returnData: AlgebraInterfaceMulticall.ResultStructOutput[];
        lastSuccessIndex: bigint;
      }
    ],
    "nonpayable"
  >;

  filters: {};
}
