/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ITickLens {
  export type PopulatedTickStruct = {
    tick: BigNumberish;
    liquidityNet: BigNumberish;
    liquidityGross: BigNumberish;
  };

  export type PopulatedTickStructOutput = [
    tick: bigint,
    liquidityNet: bigint,
    liquidityGross: bigint
  ] & { tick: bigint; liquidityNet: bigint; liquidityGross: bigint };
}

export interface TickLensInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getClosestActiveTicks"
      | "getNextActiveTicks"
      | "getPopulatedTicksInWord"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getClosestActiveTicks",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNextActiveTicks",
    values: [AddressLike, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getPopulatedTicksInWord",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getClosestActiveTicks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNextActiveTicks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPopulatedTicksInWord",
    data: BytesLike
  ): Result;
}

export interface TickLens extends BaseContract {
  connect(runner?: ContractRunner | null): TickLens;
  waitForDeployment(): Promise<this>;

  interface: TickLensInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getClosestActiveTicks: TypedContractMethod<
    [pool: AddressLike, targetTick: BigNumberish],
    [
      [ITickLens.PopulatedTickStructOutput, ITickLens.PopulatedTickStructOutput]
    ],
    "view"
  >;

  getNextActiveTicks: TypedContractMethod<
    [
      pool: AddressLike,
      startingTick: BigNumberish,
      amount: BigNumberish,
      upperDirection: boolean
    ],
    [ITickLens.PopulatedTickStructOutput[]],
    "view"
  >;

  getPopulatedTicksInWord: TypedContractMethod<
    [pool: AddressLike, tickTableIndex: BigNumberish],
    [ITickLens.PopulatedTickStructOutput[]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getClosestActiveTicks"
  ): TypedContractMethod<
    [pool: AddressLike, targetTick: BigNumberish],
    [
      [ITickLens.PopulatedTickStructOutput, ITickLens.PopulatedTickStructOutput]
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNextActiveTicks"
  ): TypedContractMethod<
    [
      pool: AddressLike,
      startingTick: BigNumberish,
      amount: BigNumberish,
      upperDirection: boolean
    ],
    [ITickLens.PopulatedTickStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPopulatedTicksInWord"
  ): TypedContractMethod<
    [pool: AddressLike, tickTableIndex: BigNumberish],
    [ITickLens.PopulatedTickStructOutput[]],
    "view"
  >;

  filters: {};
}
