/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export declare namespace IReflexRouter {
  export type ExecuteParamsStruct = {
    target: AddressLike;
    value: BigNumberish;
    callData: BytesLike;
  };

  export type ExecuteParamsStructOutput = [
    target: string,
    value: bigint,
    callData: string
  ] & { target: string; value: bigint; callData: string };

  export type BackrunParamsStruct = {
    triggerPoolId: BytesLike;
    swapAmountIn: BigNumberish;
    token0In: boolean;
    recipient: AddressLike;
    configId: BytesLike;
  };

  export type BackrunParamsStructOutput = [
    triggerPoolId: string,
    swapAmountIn: bigint,
    token0In: boolean,
    recipient: string,
    configId: string
  ] & {
    triggerPoolId: string;
    swapAmountIn: bigint;
    token0In: boolean;
    recipient: string;
    configId: string;
  };
}

export interface IReflexRouterInterface extends Interface {
  getFunction(
    nameOrSignature: "backrunedExecute" | "getReflexAdmin" | "triggerBackrun"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "BackrunExecuted"): EventFragment;

  encodeFunctionData(
    functionFragment: "backrunedExecute",
    values: [
      IReflexRouter.ExecuteParamsStruct,
      IReflexRouter.BackrunParamsStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getReflexAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "triggerBackrun",
    values: [BytesLike, BigNumberish, boolean, AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "backrunedExecute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReflexAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "triggerBackrun",
    data: BytesLike
  ): Result;
}

export namespace BackrunExecutedEvent {
  export type InputTuple = [
    triggerPoolId: BytesLike,
    swapAmountIn: BigNumberish,
    token0In: boolean,
    quoteProfit: BigNumberish,
    profit: BigNumberish,
    profitToken: AddressLike,
    recipient: AddressLike
  ];
  export type OutputTuple = [
    triggerPoolId: string,
    swapAmountIn: bigint,
    token0In: boolean,
    quoteProfit: bigint,
    profit: bigint,
    profitToken: string,
    recipient: string
  ];
  export interface OutputObject {
    triggerPoolId: string;
    swapAmountIn: bigint;
    token0In: boolean;
    quoteProfit: bigint;
    profit: bigint;
    profitToken: string;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IReflexRouter extends BaseContract {
  connect(runner?: ContractRunner | null): IReflexRouter;
  waitForDeployment(): Promise<this>;

  interface: IReflexRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  backrunedExecute: TypedContractMethod<
    [
      executeParams: IReflexRouter.ExecuteParamsStruct,
      backrunParams: IReflexRouter.BackrunParamsStruct[]
    ],
    [
      [boolean, string, bigint[], string[]] & {
        success: boolean;
        returnData: string;
        profits: bigint[];
        profitTokens: string[];
      }
    ],
    "payable"
  >;

  getReflexAdmin: TypedContractMethod<[], [string], "view">;

  triggerBackrun: TypedContractMethod<
    [
      triggerPoolId: BytesLike,
      swapAmountIn: BigNumberish,
      token0In: boolean,
      recipient: AddressLike,
      configId: BytesLike
    ],
    [[bigint, string] & { profit: bigint; profitToken: string }],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "backrunedExecute"
  ): TypedContractMethod<
    [
      executeParams: IReflexRouter.ExecuteParamsStruct,
      backrunParams: IReflexRouter.BackrunParamsStruct[]
    ],
    [
      [boolean, string, bigint[], string[]] & {
        success: boolean;
        returnData: string;
        profits: bigint[];
        profitTokens: string[];
      }
    ],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getReflexAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "triggerBackrun"
  ): TypedContractMethod<
    [
      triggerPoolId: BytesLike,
      swapAmountIn: BigNumberish,
      token0In: boolean,
      recipient: AddressLike,
      configId: BytesLike
    ],
    [[bigint, string] & { profit: bigint; profitToken: string }],
    "nonpayable"
  >;

  getEvent(
    key: "BackrunExecuted"
  ): TypedContractEvent<
    BackrunExecutedEvent.InputTuple,
    BackrunExecutedEvent.OutputTuple,
    BackrunExecutedEvent.OutputObject
  >;

  filters: {
    "BackrunExecuted(bytes32,uint112,bool,uint256,uint256,address,address)": TypedContractEvent<
      BackrunExecutedEvent.InputTuple,
      BackrunExecutedEvent.OutputTuple,
      BackrunExecutedEvent.OutputObject
    >;
    BackrunExecuted: TypedContractEvent<
      BackrunExecutedEvent.InputTuple,
      BackrunExecutedEvent.OutputTuple,
      BackrunExecutedEvent.OutputObject
    >;
  };
}
