/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IBasePluginV2FactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ALGEBRA_BASE_PLUGIN_FACTORY_ADMINISTRATOR"
      | "afterCreatePoolHook"
      | "algebraFactory"
      | "beforeCreatePoolHook"
      | "createPluginForExistingPool"
      | "defaultBaseFee"
      | "farmingAddress"
      | "pluginByPool"
      | "setDefaultBaseFee"
      | "setFarmingAddress"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "DefaultBaseFee" | "FarmingAddress"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ALGEBRA_BASE_PLUGIN_FACTORY_ADMINISTRATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "afterCreatePoolHook",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "algebraFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "beforeCreatePoolHook",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createPluginForExistingPool",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultBaseFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "farmingAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pluginByPool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultBaseFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFarmingAddress",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "ALGEBRA_BASE_PLUGIN_FACTORY_ADMINISTRATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "afterCreatePoolHook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "algebraFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beforeCreatePoolHook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPluginForExistingPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultBaseFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "farmingAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pluginByPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultBaseFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFarmingAddress",
    data: BytesLike
  ): Result;
}

export namespace DefaultBaseFeeEvent {
  export type InputTuple = [newDefaultBaseFee: BigNumberish];
  export type OutputTuple = [newDefaultBaseFee: bigint];
  export interface OutputObject {
    newDefaultBaseFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FarmingAddressEvent {
  export type InputTuple = [newFarmingAddress: AddressLike];
  export type OutputTuple = [newFarmingAddress: string];
  export interface OutputObject {
    newFarmingAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IBasePluginV2Factory extends BaseContract {
  connect(runner?: ContractRunner | null): IBasePluginV2Factory;
  waitForDeployment(): Promise<this>;

  interface: IBasePluginV2FactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ALGEBRA_BASE_PLUGIN_FACTORY_ADMINISTRATOR: TypedContractMethod<
    [],
    [string],
    "view"
  >;

  afterCreatePoolHook: TypedContractMethod<
    [plugin: AddressLike, pool: AddressLike, deployer: AddressLike],
    [void],
    "nonpayable"
  >;

  algebraFactory: TypedContractMethod<[], [string], "view">;

  beforeCreatePoolHook: TypedContractMethod<
    [
      pool: AddressLike,
      creator: AddressLike,
      deployer: AddressLike,
      token0: AddressLike,
      token1: AddressLike,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  createPluginForExistingPool: TypedContractMethod<
    [token0: AddressLike, token1: AddressLike],
    [string],
    "nonpayable"
  >;

  defaultBaseFee: TypedContractMethod<[], [bigint], "view">;

  farmingAddress: TypedContractMethod<[], [string], "view">;

  pluginByPool: TypedContractMethod<[pool: AddressLike], [string], "view">;

  setDefaultBaseFee: TypedContractMethod<
    [newDefaultBaseFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFarmingAddress: TypedContractMethod<
    [newFarmingAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ALGEBRA_BASE_PLUGIN_FACTORY_ADMINISTRATOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "afterCreatePoolHook"
  ): TypedContractMethod<
    [plugin: AddressLike, pool: AddressLike, deployer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "algebraFactory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "beforeCreatePoolHook"
  ): TypedContractMethod<
    [
      pool: AddressLike,
      creator: AddressLike,
      deployer: AddressLike,
      token0: AddressLike,
      token1: AddressLike,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createPluginForExistingPool"
  ): TypedContractMethod<
    [token0: AddressLike, token1: AddressLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "defaultBaseFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "farmingAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pluginByPool"
  ): TypedContractMethod<[pool: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "setDefaultBaseFee"
  ): TypedContractMethod<
    [newDefaultBaseFee: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFarmingAddress"
  ): TypedContractMethod<
    [newFarmingAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DefaultBaseFee"
  ): TypedContractEvent<
    DefaultBaseFeeEvent.InputTuple,
    DefaultBaseFeeEvent.OutputTuple,
    DefaultBaseFeeEvent.OutputObject
  >;
  getEvent(
    key: "FarmingAddress"
  ): TypedContractEvent<
    FarmingAddressEvent.InputTuple,
    FarmingAddressEvent.OutputTuple,
    FarmingAddressEvent.OutputObject
  >;

  filters: {
    "DefaultBaseFee(uint16)": TypedContractEvent<
      DefaultBaseFeeEvent.InputTuple,
      DefaultBaseFeeEvent.OutputTuple,
      DefaultBaseFeeEvent.OutputObject
    >;
    DefaultBaseFee: TypedContractEvent<
      DefaultBaseFeeEvent.InputTuple,
      DefaultBaseFeeEvent.OutputTuple,
      DefaultBaseFeeEvent.OutputObject
    >;

    "FarmingAddress(address)": TypedContractEvent<
      FarmingAddressEvent.InputTuple,
      FarmingAddressEvent.OutputTuple,
      FarmingAddressEvent.OutputObject
    >;
    FarmingAddress: TypedContractEvent<
      FarmingAddressEvent.InputTuple,
      FarmingAddressEvent.OutputTuple,
      FarmingAddressEvent.OutputObject
    >;
  };
}
