/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type AlgebraFeeConfigurationStruct = {
  alpha1: BigNumberish;
  alpha2: BigNumberish;
  beta1: BigNumberish;
  beta2: BigNumberish;
  gamma1: BigNumberish;
  gamma2: BigNumberish;
  baseFee: BigNumberish;
};

export type AlgebraFeeConfigurationStructOutput = [
  alpha1: bigint,
  alpha2: bigint,
  beta1: bigint,
  beta2: bigint,
  gamma1: bigint,
  gamma2: bigint,
  baseFee: bigint
] & {
  alpha1: bigint;
  alpha2: bigint;
  beta1: bigint;
  beta2: bigint;
  gamma1: bigint;
  gamma2: bigint;
  baseFee: bigint;
};

export interface IBasePluginV3FactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ALGEBRA_BASE_PLUGIN_FACTORY_ADMINISTRATOR"
      | "afterCreatePoolHook"
      | "algebraFactory"
      | "beforeCreatePoolHook"
      | "createPluginForExistingCustomPool"
      | "defaultFeeConfiguration"
      | "farmingAddress"
      | "feeDiscountRegistry"
      | "pluginByPool"
      | "securityRegistry"
      | "setDefaultFeeConfiguration"
      | "setFarmingAddress"
      | "setFeeDiscountRegistry"
      | "setSecurityRegistry"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DefaultFeeConfiguration"
      | "FarmingAddress"
      | "FeeDiscountRegistry"
      | "PluginDeployer"
      | "ReflexConfig"
      | "SecurityRegistry"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ALGEBRA_BASE_PLUGIN_FACTORY_ADMINISTRATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "afterCreatePoolHook",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "algebraFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "beforeCreatePoolHook",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createPluginForExistingCustomPool",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultFeeConfiguration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "farmingAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feeDiscountRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pluginByPool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "securityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultFeeConfiguration",
    values: [AlgebraFeeConfigurationStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setFarmingAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeDiscountRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSecurityRegistry",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "ALGEBRA_BASE_PLUGIN_FACTORY_ADMINISTRATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "afterCreatePoolHook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "algebraFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beforeCreatePoolHook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPluginForExistingCustomPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultFeeConfiguration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "farmingAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeDiscountRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pluginByPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "securityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultFeeConfiguration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFarmingAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeDiscountRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSecurityRegistry",
    data: BytesLike
  ): Result;
}

export namespace DefaultFeeConfigurationEvent {
  export type InputTuple = [newConfig: AlgebraFeeConfigurationStruct];
  export type OutputTuple = [newConfig: AlgebraFeeConfigurationStructOutput];
  export interface OutputObject {
    newConfig: AlgebraFeeConfigurationStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FarmingAddressEvent {
  export type InputTuple = [newFarmingAddress: AddressLike];
  export type OutputTuple = [newFarmingAddress: string];
  export interface OutputObject {
    newFarmingAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeDiscountRegistryEvent {
  export type InputTuple = [registry: AddressLike];
  export type OutputTuple = [registry: string];
  export interface OutputObject {
    registry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PluginDeployerEvent {
  export type InputTuple = [deployer: AddressLike];
  export type OutputTuple = [deployer: string];
  export interface OutputObject {
    deployer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReflexConfigEvent {
  export type InputTuple = [
    reflexRouter: AddressLike,
    reflexConfigId: BytesLike
  ];
  export type OutputTuple = [reflexRouter: string, reflexConfigId: string];
  export interface OutputObject {
    reflexRouter: string;
    reflexConfigId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SecurityRegistryEvent {
  export type InputTuple = [securityRegistry: AddressLike];
  export type OutputTuple = [securityRegistry: string];
  export interface OutputObject {
    securityRegistry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IBasePluginV3Factory extends BaseContract {
  connect(runner?: ContractRunner | null): IBasePluginV3Factory;
  waitForDeployment(): Promise<this>;

  interface: IBasePluginV3FactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ALGEBRA_BASE_PLUGIN_FACTORY_ADMINISTRATOR: TypedContractMethod<
    [],
    [string],
    "view"
  >;

  afterCreatePoolHook: TypedContractMethod<
    [plugin: AddressLike, pool: AddressLike, deployer: AddressLike],
    [void],
    "nonpayable"
  >;

  algebraFactory: TypedContractMethod<[], [string], "view">;

  beforeCreatePoolHook: TypedContractMethod<
    [
      pool: AddressLike,
      creator: AddressLike,
      deployer: AddressLike,
      token0: AddressLike,
      token1: AddressLike,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  createPluginForExistingCustomPool: TypedContractMethod<
    [token0: AddressLike, token1: AddressLike, customPoolDeployer: AddressLike],
    [string],
    "nonpayable"
  >;

  defaultFeeConfiguration: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        alpha1: bigint;
        alpha2: bigint;
        beta1: bigint;
        beta2: bigint;
        gamma1: bigint;
        gamma2: bigint;
        baseFee: bigint;
      }
    ],
    "view"
  >;

  farmingAddress: TypedContractMethod<[], [string], "view">;

  feeDiscountRegistry: TypedContractMethod<[], [string], "view">;

  pluginByPool: TypedContractMethod<[pool: AddressLike], [string], "view">;

  securityRegistry: TypedContractMethod<[], [string], "view">;

  setDefaultFeeConfiguration: TypedContractMethod<
    [newConfig: AlgebraFeeConfigurationStruct],
    [void],
    "nonpayable"
  >;

  setFarmingAddress: TypedContractMethod<
    [newFarmingAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setFeeDiscountRegistry: TypedContractMethod<
    [newFeeDiscountRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  setSecurityRegistry: TypedContractMethod<
    [newSecurityRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ALGEBRA_BASE_PLUGIN_FACTORY_ADMINISTRATOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "afterCreatePoolHook"
  ): TypedContractMethod<
    [plugin: AddressLike, pool: AddressLike, deployer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "algebraFactory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "beforeCreatePoolHook"
  ): TypedContractMethod<
    [
      pool: AddressLike,
      creator: AddressLike,
      deployer: AddressLike,
      token0: AddressLike,
      token1: AddressLike,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createPluginForExistingCustomPool"
  ): TypedContractMethod<
    [token0: AddressLike, token1: AddressLike, customPoolDeployer: AddressLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "defaultFeeConfiguration"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        alpha1: bigint;
        alpha2: bigint;
        beta1: bigint;
        beta2: bigint;
        gamma1: bigint;
        gamma2: bigint;
        baseFee: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "farmingAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "feeDiscountRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pluginByPool"
  ): TypedContractMethod<[pool: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "securityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setDefaultFeeConfiguration"
  ): TypedContractMethod<
    [newConfig: AlgebraFeeConfigurationStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFarmingAddress"
  ): TypedContractMethod<
    [newFarmingAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFeeDiscountRegistry"
  ): TypedContractMethod<
    [newFeeDiscountRegistry: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSecurityRegistry"
  ): TypedContractMethod<
    [newSecurityRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DefaultFeeConfiguration"
  ): TypedContractEvent<
    DefaultFeeConfigurationEvent.InputTuple,
    DefaultFeeConfigurationEvent.OutputTuple,
    DefaultFeeConfigurationEvent.OutputObject
  >;
  getEvent(
    key: "FarmingAddress"
  ): TypedContractEvent<
    FarmingAddressEvent.InputTuple,
    FarmingAddressEvent.OutputTuple,
    FarmingAddressEvent.OutputObject
  >;
  getEvent(
    key: "FeeDiscountRegistry"
  ): TypedContractEvent<
    FeeDiscountRegistryEvent.InputTuple,
    FeeDiscountRegistryEvent.OutputTuple,
    FeeDiscountRegistryEvent.OutputObject
  >;
  getEvent(
    key: "PluginDeployer"
  ): TypedContractEvent<
    PluginDeployerEvent.InputTuple,
    PluginDeployerEvent.OutputTuple,
    PluginDeployerEvent.OutputObject
  >;
  getEvent(
    key: "ReflexConfig"
  ): TypedContractEvent<
    ReflexConfigEvent.InputTuple,
    ReflexConfigEvent.OutputTuple,
    ReflexConfigEvent.OutputObject
  >;
  getEvent(
    key: "SecurityRegistry"
  ): TypedContractEvent<
    SecurityRegistryEvent.InputTuple,
    SecurityRegistryEvent.OutputTuple,
    SecurityRegistryEvent.OutputObject
  >;

  filters: {
    "DefaultFeeConfiguration(tuple)": TypedContractEvent<
      DefaultFeeConfigurationEvent.InputTuple,
      DefaultFeeConfigurationEvent.OutputTuple,
      DefaultFeeConfigurationEvent.OutputObject
    >;
    DefaultFeeConfiguration: TypedContractEvent<
      DefaultFeeConfigurationEvent.InputTuple,
      DefaultFeeConfigurationEvent.OutputTuple,
      DefaultFeeConfigurationEvent.OutputObject
    >;

    "FarmingAddress(address)": TypedContractEvent<
      FarmingAddressEvent.InputTuple,
      FarmingAddressEvent.OutputTuple,
      FarmingAddressEvent.OutputObject
    >;
    FarmingAddress: TypedContractEvent<
      FarmingAddressEvent.InputTuple,
      FarmingAddressEvent.OutputTuple,
      FarmingAddressEvent.OutputObject
    >;

    "FeeDiscountRegistry(address)": TypedContractEvent<
      FeeDiscountRegistryEvent.InputTuple,
      FeeDiscountRegistryEvent.OutputTuple,
      FeeDiscountRegistryEvent.OutputObject
    >;
    FeeDiscountRegistry: TypedContractEvent<
      FeeDiscountRegistryEvent.InputTuple,
      FeeDiscountRegistryEvent.OutputTuple,
      FeeDiscountRegistryEvent.OutputObject
    >;

    "PluginDeployer(address)": TypedContractEvent<
      PluginDeployerEvent.InputTuple,
      PluginDeployerEvent.OutputTuple,
      PluginDeployerEvent.OutputObject
    >;
    PluginDeployer: TypedContractEvent<
      PluginDeployerEvent.InputTuple,
      PluginDeployerEvent.OutputTuple,
      PluginDeployerEvent.OutputObject
    >;

    "ReflexConfig(address,bytes32)": TypedContractEvent<
      ReflexConfigEvent.InputTuple,
      ReflexConfigEvent.OutputTuple,
      ReflexConfigEvent.OutputObject
    >;
    ReflexConfig: TypedContractEvent<
      ReflexConfigEvent.InputTuple,
      ReflexConfigEvent.OutputTuple,
      ReflexConfigEvent.OutputObject
    >;

    "SecurityRegistry(address)": TypedContractEvent<
      SecurityRegistryEvent.InputTuple,
      SecurityRegistryEvent.OutputTuple,
      SecurityRegistryEvent.OutputObject
    >;
    SecurityRegistry: TypedContractEvent<
      SecurityRegistryEvent.InputTuple,
      SecurityRegistryEvent.OutputTuple,
      SecurityRegistryEvent.OutputObject
    >;
  };
}
