/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface AdaptiveFeeEchidnaTestInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkExpInvariants"
      | "checkFeeConfigPackedCorrectness"
      | "checkFeeInvariants"
      | "checkSigmoidInvariants"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "checkExpInvariants",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkFeeConfigPackedCorrectness",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "checkFeeInvariants",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "checkSigmoidInvariants",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkExpInvariants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkFeeConfigPackedCorrectness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkFeeInvariants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkSigmoidInvariants",
    data: BytesLike
  ): Result;
}

export interface AdaptiveFeeEchidnaTest extends BaseContract {
  connect(runner?: ContractRunner | null): AdaptiveFeeEchidnaTest;
  waitForDeployment(): Promise<this>;

  interface: AdaptiveFeeEchidnaTestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkExpInvariants: TypedContractMethod<
    [x: BigNumberish, gamma: BigNumberish],
    [void],
    "view"
  >;

  checkFeeConfigPackedCorrectness: TypedContractMethod<
    [
      alpha1: BigNumberish,
      alpha2: BigNumberish,
      beta1: BigNumberish,
      beta2: BigNumberish,
      gamma1: BigNumberish,
      gamma2: BigNumberish,
      baseFee: BigNumberish
    ],
    [void],
    "view"
  >;

  checkFeeInvariants: TypedContractMethod<
    [
      volatility: BigNumberish,
      alpha1: BigNumberish,
      alpha2: BigNumberish,
      beta1: BigNumberish,
      beta2: BigNumberish,
      gamma1: BigNumberish,
      gamma2: BigNumberish,
      baseFee: BigNumberish
    ],
    [bigint],
    "view"
  >;

  checkSigmoidInvariants: TypedContractMethod<
    [
      x: BigNumberish,
      gamma: BigNumberish,
      alpha: BigNumberish,
      beta: BigNumberish
    ],
    [void],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkExpInvariants"
  ): TypedContractMethod<
    [x: BigNumberish, gamma: BigNumberish],
    [void],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkFeeConfigPackedCorrectness"
  ): TypedContractMethod<
    [
      alpha1: BigNumberish,
      alpha2: BigNumberish,
      beta1: BigNumberish,
      beta2: BigNumberish,
      gamma1: BigNumberish,
      gamma2: BigNumberish,
      baseFee: BigNumberish
    ],
    [void],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkFeeInvariants"
  ): TypedContractMethod<
    [
      volatility: BigNumberish,
      alpha1: BigNumberish,
      alpha2: BigNumberish,
      beta1: BigNumberish,
      beta2: BigNumberish,
      gamma1: BigNumberish,
      gamma2: BigNumberish,
      baseFee: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkSigmoidInvariants"
  ): TypedContractMethod<
    [
      x: BigNumberish,
      gamma: BigNumberish,
      alpha: BigNumberish,
      beta: BigNumberish
    ],
    [void],
    "view"
  >;

  filters: {};
}
