/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface VolatilityOracleEchidnaTestInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "advanceTime"
      | "checkAveragesNotOverflow"
      | "checkTimeWeightedAveragesAlwaysFitsType"
      | "checkTimeWeightedResultAssertions"
      | "checkTwoAdjacentTimepointsTickCumulativeModTimeElapsedAlways0"
      | "initialize"
      | "update"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "advanceTime",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkAveragesNotOverflow",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkTimeWeightedAveragesAlwaysFitsType",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkTimeWeightedResultAssertions",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkTwoAdjacentTimepointsTickCumulativeModTimeElapsedAlways0",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "update",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "advanceTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkAveragesNotOverflow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkTimeWeightedAveragesAlwaysFitsType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkTimeWeightedResultAssertions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkTwoAdjacentTimepointsTickCumulativeModTimeElapsedAlways0",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "update", data: BytesLike): Result;
}

export interface VolatilityOracleEchidnaTest extends BaseContract {
  connect(runner?: ContractRunner | null): VolatilityOracleEchidnaTest;
  waitForDeployment(): Promise<this>;

  interface: VolatilityOracleEchidnaTestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  advanceTime: TypedContractMethod<[by: BigNumberish], [void], "nonpayable">;

  checkAveragesNotOverflow: TypedContractMethod<[], [void], "view">;

  checkTimeWeightedAveragesAlwaysFitsType: TypedContractMethod<
    [secondsAgo: BigNumberish],
    [void],
    "view"
  >;

  checkTimeWeightedResultAssertions: TypedContractMethod<
    [secondsAgo0: BigNumberish, secondsAgo1: BigNumberish],
    [void],
    "view"
  >;

  checkTwoAdjacentTimepointsTickCumulativeModTimeElapsedAlways0: TypedContractMethod<
    [index: BigNumberish],
    [void],
    "view"
  >;

  initialize: TypedContractMethod<
    [time: BigNumberish, tick: BigNumberish],
    [void],
    "nonpayable"
  >;

  update: TypedContractMethod<
    [advanceTimeBy: BigNumberish, tick: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "advanceTime"
  ): TypedContractMethod<[by: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkAveragesNotOverflow"
  ): TypedContractMethod<[], [void], "view">;
  getFunction(
    nameOrSignature: "checkTimeWeightedAveragesAlwaysFitsType"
  ): TypedContractMethod<[secondsAgo: BigNumberish], [void], "view">;
  getFunction(
    nameOrSignature: "checkTimeWeightedResultAssertions"
  ): TypedContractMethod<
    [secondsAgo0: BigNumberish, secondsAgo1: BigNumberish],
    [void],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkTwoAdjacentTimepointsTickCumulativeModTimeElapsedAlways0"
  ): TypedContractMethod<[index: BigNumberish], [void], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [time: BigNumberish, tick: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "update"
  ): TypedContractMethod<
    [advanceTimeBy: BigNumberish, tick: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
