/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface VolatilityOracleMathEchidnaTestInterface extends Interface {
  getFunction(
    nameOrSignature: "checkLteConsideringOverflow" | "checkVolatilityOnRange"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "checkLteConsideringOverflow",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkVolatilityOnRange",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkLteConsideringOverflow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkVolatilityOnRange",
    data: BytesLike
  ): Result;
}

export interface VolatilityOracleMathEchidnaTest extends BaseContract {
  connect(runner?: ContractRunner | null): VolatilityOracleMathEchidnaTest;
  waitForDeployment(): Promise<this>;

  interface: VolatilityOracleMathEchidnaTestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkLteConsideringOverflow: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish, currentTime: BigNumberish],
    [void],
    "view"
  >;

  checkVolatilityOnRange: TypedContractMethod<
    [
      dt: BigNumberish,
      tick0: BigNumberish,
      tick1: BigNumberish,
      avgTick0: BigNumberish,
      avgTick1: BigNumberish
    ],
    [void],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkLteConsideringOverflow"
  ): TypedContractMethod<
    [a: BigNumberish, b: BigNumberish, currentTime: BigNumberish],
    [void],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkVolatilityOnRange"
  ): TypedContractMethod<
    [
      dt: BigNumberish,
      tick0: BigNumberish,
      tick1: BigNumberish,
      avgTick0: BigNumberish,
      avgTick1: BigNumberish
    ],
    [void],
    "view"
  >;

  filters: {};
}
